### ISSUE TITLE
is it possible to use it with AzureGermanCloud etc.?

### ISSUE THREAD

**Issue by binlan** [jenkinsci/azure-ad-plugin#10]
while trying to use it with the german cloud i just get the following error:
"Confidential Client is not supported in Cross Cloud request"

**Comment by ArieShout** [comment]
Hi @binlan , we developed the plugin on the public Azure cloud, but didn't check on the national Azure cloud.
We had backlog to check the national cloud compatibility for the Azure Jenkins plugins, however, currently there is no ETA for the landing.

**Comment by yungezz** [comment]
close the issue since not supporting non-public azure cloud. so far there's no plan yet.

**Comment by basmussen** [comment]
+1
