### ISSUE TITLE
Can't perform REST queries if AzureAD user doesn't exist explicitly in Auth Matrix

### ISSUE THREAD

**Issue by ep4sh** [jenkinsci/azure-ad-plugin#101]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.263.2
AzureAD plugin: 1.2.1

```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Centos 7
```

### Reproduction steps
My user has been added to the AzureAD group, this group was mapped with admin permissions to Jenkins.
The user doesn't exist explicitly in Jenkins Auth Matrix.

query1:
```
curl -XPOST -u "me@company.com:TOKEN"  https://JENKINS_URL/job/devops/job/docker/build
```

result1:
```
<h1>Access Denied</h1><p class="error">me@company.com is missing the Overall/Read permission</div>
```

At the same time, I have a service account (non-real user), **which has been added explicitly to the Jenkins Auth Matrix.**
If I perform a query - everything works as expected.  

query2:
```
curl -XPOST -u "sevice_account@company.com:TOKEN"  https://JENKINS_URL/job/devops/job/docker/build
```

result2:
```
  (no answer - that is 200 OK)
```

I figure out that I have to add all AzureAD group's users explicitly to the Jenkins Auth Matrix to have for all of the AzureAD users capabilities to run jobs via REST API. 
Seems the AzureAD plugin knows nothing about the particular user when it **has no entry in Jenkins Auth Matrix** and you trying to trigger REST.

Thanks in advance,
Pasha.

**Comment by hikkyXII** [comment]
Hello! Seems related to #63 and maybe #82

**Comment by ep4sh** [comment]
@hikkyXII hi, right, looks close to #82

**Comment by hikkyXII** [comment]
As I see it, for some kings of actions Jenkins is checking user permissions by **email** but Azure AD plugin gives only **Azure User ID**
