### ISSUE TITLE
Enabling support for Job DSL plugin

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-ad-plugin#104]
<p>It's currently not possible to configure AzureAdAuthorizationMatrix property for either folders or jobs using the <a href="https://plugins.jenkins.io/job-dsl" class="external-link" target="_blank" rel="nofollow noopener">https://plugins.jenkins.io/job-dsl</a></p>
<i>[JENKINS-64858] created by mmchr</i>

**Comment by baowei** [comment]
@xuzhang3   Is it possible to add this [PR](https://github.com/jenkinsci/azure-ad-plugin/pull/99) in Release 1.2.4?

**Comment by timja** [comment]
I aim to look at that PR soon

**Comment by timja** [comment]
closed in https://github.com/jenkinsci/azure-ad-plugin/pull/99

**Comment by SomaSharathSurya** [comment]
@timja It seems to be working good for folders and freeStyleJob, but doesn't work for a pipelineJob. Could the DSL support be added for a pipelineJob too ?

Eg: The below configuration seems to be non-functional. I'm running with Job DSL Plugin 1.77 version.

pipelineJob('project-a/example') {
  properties {
    azureAdAuthorizationMatrix {
      inheritanceStrategy {
        inheriting()
      }
      permissions(['hudson.model.Item.Workspace:authenticated'])
    }
  }
}

Please let me know for any additional details, if required. Thanks

**Comment by timja** [comment]
I can't see any reason it wouldn't work for pipeline from a brief look at the code, @hrmohr any insights?

**Comment by SomaSharathSurya** [comment]
@timja Please disregard my earlier comment. It seems to be working.

I have a different case, where I try to amend the configuration on an existing DSL script and it doesn't seem to work. I'm investigating it now, and will share the details once I figure out the issue. Thanks for the quick response.

**Comment by SomaSharathSurya** [comment]
Hi @timja  My bad, It's a misconfiguration from my end. I can confirm it's all good and working. Thank you
