### ISSUE TITLE
Access Email value for a specific user

### ISSUE THREAD

**Issue by agaudreault-jive** [jenkinsci/azure-ad-plugin#115]
#### Problem 

Currently, it does not seem possible to access the email value outside the `doFinishLogin` for a specific user. 

#### Context

I am trying to define a `MailAddressResolver` extension so the Email property is set to the email value of the `AzureAdUser`. This way, we can have the user email and use the method `slackUserIdFromEmail`. In our case, our slack in not behind the same AD as our jenkins instance so the user id does not correspond.

When I try the following code, I get an error and I am not able to find a way to retrieve the email. I could parse the description, but that code would be very error prone.

Script to execute in console:
```groovy
import hudson.model.User

def u = User.getById("user@domain.com", false)
def userDetails = u.getUserDetailsForImpersonation2()

println userDetails
```
Returns
```
hudson.model.User$LegitimateButUnknownUserDetails [Username=user@domain.com, Password=[PROTECTED], Enabled=true, AccountNonExpired=true, credentialsNonExpired=true, AccountNonLocked=true, Granted Authorities=[authenticated]]
```
In the logs, I have
```
The user user@domain.com may or may not exist in the SecurityRealm, so we provide minimum access
```

The code generating the log is
https://github.com/jenkinsci/jenkins/blob/7c0d4df8cb6c2b5621b8e71daee6773b1e47715d/core/src/main/java/hudson/model/User.java#L402-L407

### Implementation idea

- This plugin could set a custom property on the User that would contain the AzureAdUser object. This way, we could easily retrieve the user information without relying on the description. 

- Another option could be to have `loadUserByUsername` method implemented. It seems like it is related to https://github.com/jenkinsci/azure-ad-plugin/pull/112

- This plugin could also add a dependency to the Mailer plugin and set the property

**Comment by timja** [comment]
Shouldn't the plugin just set the email?

Needs to add a https://github.com/jenkinsci/mailer-plugin/blob/master/src/main/java/hudson/tasks/Mailer.java#L742

e.g. https://github.com/jenkinsci/ldap-plugin/blob/de742b360d0824a8a19156ebec947131d4e25418/src/main/java/hudson/security/LDAPSecurityRealm.java#L813

**Comment by agaudreault-jive** [comment]
> Shouldn't the plugin just set the email?

Yeah I think this is the most efficient way to do it if you are open to add a dependency to the Mailer plugin.

**Comment by timja** [comment]
Yeah that’s fine

**Comment by timja** [comment]
Also the line:

> The user user@domain.com may or may not exist in the SecurityRealm, so we provide minimum access

Should be fixed in the latest release

**Comment by agaudreault-jive** [comment]
I'll create a PR. Thanks for the LDAP plugin example, should be easy enough.
