### ISSUE TITLE
Jenkins log out signs off every Microsoft365 application

### ISSUE THREAD

**Issue by joaonatividade-vakt** [jenkinsci/azure-ad-plugin#124]
Hi guys!

### Feature Request
**When** logging out from Jenkins
**I want** the sign out to take effect on Jenkins only
**So that** All remaining Microsoft 365 applications (e.g. Outlook) keep me signed in.

P.S. If this feature already exists, please let me know how to configure it. For the record, [these were the guidelines](https://plugins.jenkins.io/azure-ad/#documentation) I followed for the Azure AD plugin setup. 

Thank you in advance. 
Cheers, 
João Natividade

**Comment by timja** [comment]
Yeah I would like this too, it's been annoying me, hopefully not too hard to disable.

**Comment by joaonatividade-vakt** [comment]
@timja, just did it: https://github.com/jenkinsci/azure-ad-plugin/issues/127.
