### ISSUE TITLE
Being redirected to 'logged out' page that instead of the 'home page'

### ISSUE THREAD

**Issue by joaonatividade-vakt** [jenkinsci/azure-ad-plugin#127]
Hi @timja!

First of all, let me tell you how impressed I am for the brevity in the answers you've been given me. Really remarkable! 

As for this new feature request, it's a follow-up of the following issue: https://github.com/jenkinsci/azure-ad-plugin/issues/124:

**When** logging out from Jenkins
**I want** the sign out to redirect me to a logout page with no changes required in the existing _Authorization Matrix_
**So that** I don't comprise security

Thank you in advance.
Cheers,
João Natividade

**Comment by joaonatividade-vakt** [comment]
Hi @timja,


https://user-images.githubusercontent.com/58938230/117954166-a9865800-b30e-11eb-8eed-abe4bf35c1c8.mov

This is the behavior I'm getting when logging back in. I do get logged out and redirected to the logout page when I hit "log out", but then I'm getting logged in without hitting the "log in" button. Could you please have a look? Can I help somehow? 

Regards,
João Natividade

**Comment by timja** [comment]
If you hit any protected page you will automatically get logged in, but your session has been destroyed on log out.

If you log out of Azure AD you will get prompted to log in

**Comment by joaonatividade-vakt** [comment]
@timja I'm OK with that, thank you once again!
Cheers
