### ISSUE TITLE
AADSTS90056: This endpoint only accepts POST requests. Received a GET request.

### ISSUE THREAD

**Issue by Attoy** [jenkinsci/azure-ad-plugin#13]
Don't really know if it's a plug-in issue or an AAD one. I followed the instruction in the plugin page to setup the plugin and the web app, however whenever I try to log I always receive this error:`AADSTS90056: This endpoint only accepts POST requests. Received a GET request.`
Any suggestion on how to fix it or where I can find a solution?
Thanks

**Comment by Attoy** [comment]
It appears it was a mistake on my side, a typo on the URL which I discovered only after a couple of days of wasted time spent on troubleshooting was the culprit. I close this issue. I apologize.

**Comment by nagharaaj** [comment]
AADSTS90056: This endpoint only accepts POST requests. Received a GET request.
i have same issue but  i don't  know which URL i want to be change

**Comment by charlesroddie** [comment]
@Attoy what URL did you fix?
