### ISSUE TITLE
Multi-tenant App Registrations

### ISSUE THREAD

**Issue by snooyen** [jenkinsci/azure-ad-plugin#133]
### Feature Request

Just wondering if this plugin supports multi-tenant app registrations or not?

**Comment by timja** [comment]
No it does not.

what’s your use-case for it?

I believe it’s normally more for SaaS services, have you got multiple tenants you want to auth against?

**Comment by snooyen** [comment]
Yep, we wanted to be able to share our Jenkins deployments across a few tenants but I suppose we'll have to come up with another solution here then.

Thanks!
