### ISSUE TITLE
Agent permissions

### ISSUE THREAD

**Issue by StefanSpieker** [jenkinsci/azure-ad-plugin#134]
### Feature Request

Currently it is not possible with the Azure AD plugin to configure the rights on agent level. The [matrix-auth plugin](https://plugins.jenkins.io/matrix-auth/) is capable of doing so. It would be great to also have this functionality within the Azure AD plugin.

I guess as a boilerplate you could use [AuthorizationMatrixNodeProperty.java](https://github.com/jenkinsci/matrix-auth-plugin/blob/master/src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodeProperty.java)

**Comment by timja** [comment]
The authorization strategy here is just a helper so this shouldn't block anything, you can always use one of the other ones see https://github.com/jenkinsci/azure-ad-plugin#authorization

**Comment by StefanSpieker** [comment]
I'm missing the permission in the agent config. How can I set this?
![image](https://user-images.githubusercontent.com/22742658/120148635-d41a5100-c1e8-11eb-9381-dc7d2ee78419.png)

**Comment by timja** [comment]
Is your authz set to project based security?

**Comment by StefanSpieker** [comment]
@timja I will have time tomorrow. Thanks a lot 👍

**Comment by StefanSpieker** [comment]
@timja I installed the plugin and it seems to work, I notices some stack traces in the log, but that might be unrelated to this feature:

> 17, 2021 1:02:04 PM SEVERE com.microsoft.graph.logger.DefaultLogger logError
Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: Request_ResourceNotFound
Error message: Resource 'xyz-jenkins-q' does not exist or one of its queried reference-property objects are not present.
>GET https://graph.microsoft.com/v1.0/users/xyz-jenkins-q
>SdkVersion : graph-java/v3.8.0
>404 : Not Found
>[...]
>[Some information was truncated for brevity, enable debug logging for more details]

Maybe the App registration lacks some rights.

**Comment by timja** [comment]
It’s unrelated I have a fix in progress for that
