### ISSUE TITLE
Question: Using SSO without exposing Jenkins

### ISSUE THREAD

**Issue by g3n35i5** [jenkinsci/azure-ad-plugin#138]
Hello all!

I would like to know if it is possible to use SSO without exposing the whole Jenkins host. 

**Setup**

Jenkins host <-> reverse proxy <-> firewall <-> internet.

**Which works so far**
SSO by exposing the complete host

**What I would like to have**
Using SSO but make jenkins only accessible from the local network or VPN.

Can this work at all? And which redirect URLs do I have to set then?

**Comment by timja** [comment]
AzureAD doesn't communicate with Jenkins directly

It's all browser based or backchannel initiated from Jenkins.

Your browser needs to be able to reach the microsoft login url
and Jenkins needs to be able to reach the required URLs
