### ISSUE TITLE
People-Picker does not show list of users in project-based security after upgrade to 168.ve6e7e368dbf6

### ISSUE THREAD

**Issue by bartsqueezy** [jenkinsci/azure-ad-plugin#146]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.289.1
OS: Linux - 5.4.0-1047-azure
---
blueocean-autofavorite:1.2.4
allure-jenkins-plugin:2.29.0
workflow-scm-step:2.13
cloudbees-folder:6.15
trilead-api:1.0.13
matrix-auth:2.6.7
bootstrap4-api:4.6.0-3
kubernetes-credentials:0.9.0
branch-api:2.6.4
jdk-tool:1.0
pubsub-light:1.16
workflow-multibranch:2.26
blueocean-core-js:1.24.7
workflow-basic-steps:2.23
blueocean-rest:1.24.7
variant:1.4
git-client:3.7.2
javadoc:1.6
jenkins-design-language:1.24.7
git-server:1.9
favorite:2.3.3
blueocean-commons:1.24.7
github-api:1.123
blueocean-personalization:1.24.7
email-ext:2.83
code-coverage-api:1.4.0
pipeline-input-step:2.12
htmlpublisher:1.25
cloudbees-bitbucket-branch-source:2.9.9
snakeyaml-api:1.29.1
veracode-scan:21.6.13.0
structs:1.23
token-macro:2.15
authorize-project:1.4.0
pipeline-utility-steps:2.8.0
blueocean-jwt:1.24.7
kubernetes-client-api:5.4.1
strict-crumb-issuer:2.1.0
lockable-resources:2.11
bootstrap5-api:5.0.1-2
credentials:2.5
authentication-tokens:1.4
mstest:1.0.0
gradle:1.36
checks-api:1.7.0
sse-gateway:1.24
sonar:2.13.1
workflow-aggregator:2.6
simple-theme-plugin:0.6
workflow-support:3.8
pipeline-stage-view:2.19
mailer:1.34
configuration-as-code:1.51
jjwt-api:0.11.2-9.c8b45b8bb173
workflow-api:2.45
pipeline-milestone-step:1.3.2
pipeline-build-step:2.13
sshd:3.0.3
junit:1.50
ant:1.11
blueocean-web:1.24.7
jquery3-api:3.6.0-1
plugin-util-api:2.3.0
docker-workflow:1.26
gitlab-branch-source:1.5.7
maven-plugin:3.12
scm-api:2.6.4
blueocean-pipeline-scm-api:1.24.7
cobertura:1.16
blueocean-pipeline-editor:1.24.7
bouncycastle-api:2.20
momentjs:1.1.1
blueocean-dashboard:1.24.7
pipeline-model-definition:1.8.5
config-file-provider:3.8.0
script-security:1.77
basic-branch-build-strategies:1.3.2
echarts-api:5.1.2-2
blueocean-i18n:1.24.7
ansicolor:1.0.0
credentials-binding:1.25
workflow-cps-global-lib:2.20
github:1.33.1
azure-sdk:20.vd701043901ab
jackson2-api:2.12.3
metrics:4.0.2.8
gitlab-api:1.0.6
pipeline-model-extensions:1.8.5
jaxb:2.3.0
durable-task:1.37
popper2-api:2.5.4-2
pipeline-stage-step:2.5
popper-api:1.16.1-2
blueocean-pipeline-api-impl:1.24.7
pipeline-rest-api:2.19
blueocean-bitbucket-pipeline:1.24.7
github-branch-source:2.11.1
font-awesome-api:5.15.3-3
ssh-credentials:1.19
display-url-api:2.3.5
handy-uri-templates-2-api:2.1.8-1.0
blueocean:1.24.7
jsch:0.1.55.2
caffeine-api:2.9.1-23.v51c4e2c879c8
workflow-job:2.41
blueocean-rest-impl:1.24.7
pipeline-stage-tags-metadata:1.8.5
blueocean-events:1.24.7
blueocean-git-pipeline:1.24.7
handlebars:3.0.8
pipeline-model-api:1.8.5
data-tables-api:1.10.25-1
okhttp-api:3.14.9
kubernetes:1.30.0
ivy:2.1
copyartifact:1.46.1
Office-365-Connector:4.15.0
artifactory:3.11.4
workflow-cps:2.92
blueocean-github-pipeline:1.24.7
docker-commons:1.17
azure-ad:168.ve6e7e368dbf6
command-launcher:1.2
pipeline-graph-analysis:1.11
apache-httpcomponents-client-4-api:4.5.13-1.0
git:4.7.2
workflow-step-api:2.23
workflow-durable-task-step:2.39
blueocean-config:1.24.7
matrix-project:1.19
forensics-api:1.1.0
plain-credentials:1.7
blueocean-display-url:2.4.1
ace-editor:1.1
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
See above
```

### Reproduction steps

- Install latest azure-ad-plugin (currently `168.ve6e7e368dbf6`)
- Create a new job of type "Folder"
- In job configuration page, check "Enable project-based security"
- In the text box for "Azure User/group to add", type the name of a user

### Results

Expected result:

The people-picker component should show the list of matched users in the Azure AD tenant.

Actual result:

The component box says "We didn't find any find any matches". Checking browser request logs via Network tab in Dev Tools, it does not send any XHRs to Azure AD to look up users (which is what it does on the main Manage Credentials page). There also is no information shown in the main Jenkins logs. 

![image](https://user-images.githubusercontent.com/647029/122964923-5fe94e00-d34d-11eb-9e5c-5557c51eee3b.png)

Downgrading to version `158.v437429002c6b` restores functionality but loses the nice People Picker component 😞

**Comment by bartsqueezy** [comment]
Re-tested with `170.v0a6219442a99`, confirmed working. Thank you @timja for the quick fix, very much appreciated 🍻

**Comment by timja** [comment]
Have you saved the configuration once and reloaded the page?

**Comment by afdgtech** [comment]
> Have you saved the configuration once and reloaded the page?

Yup, I have also cleared my cache, and waited about 30 minutes for any Azyre "delay".

**Comment by aaamiiit7902** [comment]
for me the it is working, i mean the drop down but after i select and add the user, the display name is the user id not the name.
can someone help me out with this

<img width="751" alt="image" src="https://github.com/jenkinsci/azure-ad-plugin/assets/24590778/867b2620-97f6-42da-b78b-41d074e9afea">

**Comment by timja** [comment]
Can you try upgrade to the latest version? Some code was changed in that area but nothing intentionally and that bit definitely worked at least on the global security page
