### ISSUE TITLE
Email attribute returning 'null'

### ISSUE THREAD

**Issue by evertonmc** [jenkinsci/azure-ad-plugin#15]
https://github.com/jenkinsci/azure-ad-plugin/blob/e3d198d630ae4c7deaaf8497486046b0108e9eec/src/main/java/com/microsoft/jenkins/azuread/AzureAdUser.java#L52-L66

Since _email_ doesn't seem to be included in the returned claims, it should default the email property to the _uniqueName_ value, which it doesn't
![ema_ss_250](https://user-images.githubusercontent.com/5794688/44076548-debdfdae-9fa0-11e8-8431-c1cdf842ac5a.png)

**Comment by gavinfish** [comment]
@evertonmc sorry for the late response, uniqueName is not the same as email, so now we try to extract email from uniqueName. So could you please provide your uniqueName's pattern so we can check why our regular expression not work.

**Comment by evertonmc** [comment]
Hi @gavinfish 
That’s what I expected to happen, considering that the upn is a typical AAD mail address. 
First.surname@companyname.com
Thanks for having a look at it

**Comment by evertonmc** [comment]
Ok, do you know how long it take for the 0.3.1 to appear in the jenkins repo? 
0.3.0 ist completely broken after updating Jenkins to latest2.138.1

**Comment by gavinfish** [comment]
It will be available within 20 hours. 0.3.0 is broken because you upgrade azure commons version. You can downgrade azure commons version to 0.2.6 to enable ad 0.3.0 again. Version 0.3.1 will work well with the newest azure commons.

**Comment by evertonmc** [comment]
never mind. Fixed :)
