### ISSUE TITLE
403 Forbidden on Graph API

### ISSUE THREAD

**Issue by mkemmerz** [jenkinsci/azure-ad-plugin#159]
Azure AD Plugin 178.v7b93892fbe4c

Our non-admin users are not able to add other users to Jenkins folders because they are receiving a 403 Forbidden from the Graph API.

![image](https://user-images.githubusercontent.com/46575727/129340278-d91381a5-a39d-48f6-be8a-871520cb3a42.png)

We tested it with the https://jenkins.domain.com/job/XXX-projects/GraphProxy/v1.0/me 
This URL works fine for admin users and returns some JSON with Graph data. Non-admin users are receiving: 

> Access Denied
> xxx@xxx.com is missing the Overall/Administer permission

**Comment by timja** [comment]
anything useful in the system log?

**Comment by mkemmerz** [comment]
@timja It took some time but I found it in the system log:
![image](https://user-images.githubusercontent.com/46575727/129351804-1136ddc2-c2ee-4478-972b-9f19d0b1a958.png)

It seems to be related (or even the same) issue as https://github.com/jenkinsci/azure-ad-plugin/issues/156.

**Comment by timja** [comment]
I've reproduced, looks like an incomplete fix to https://github.com/jenkinsci/azure-ad-plugin/issues/146

**Comment by timja** [comment]
https://github.com/jenkinsci/azure-ad-plugin/blob/0a6219442a99dd146beba7669d55f6469ab76243/src/main/java/com/microsoft/jenkins/azuread/GraphProxy.java#L80
