### ISSUE TITLE
Can't perform REST queries using AzureAD user and token

### ISSUE THREAD

**Issue by ep4sh** [jenkinsci/azure-ad-plugin#164]
### Version report

Jenkins and plugins versions report:

```
Jenkins 2.303.1
AzureAD plugin: 180.v8b1e80e6f242

```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Centos 7
```

### Reproduction steps
My user has been added to the AzureAD group, this group was mapped with admin permissions to Jenkins.
The user doesn't exist explicitly in Jenkins Auth Matrix.

query1:
```
curl -XPOST -u "me@company.com:TOKEN"  https://JENKINS_URL/job/devops/job/docker/build
```

result1:
```
<h1>Access Denied</h1><p class="error">me@company.com is missing the Overall/Read permission</div>
```

At the same time, I have a service account (non-real user), **which has been added explicitly to the Jenkins Auth Matrix.**
If I perform a query - everything works as expected.  

query2:
```
curl -XPOST -u "sevice_account@company.com:TOKEN"  https://JENKINS_URL/job/devops/job/docker/build
```

result2:
```
  (no answer - that is 200 OK)
```

Hi everybody!

The description is the same as for https://github.com/jenkinsci/azure-ad-plugin/issues/101

I guessed it was fixed in:
https://github.com/jenkinsci/azure-ad-plugin/pull/112

Unfortunately, I still face issues with performing queries using a token and AzureAD account. Could you please suggest - it might be I missed some option? 

Thanks in advance,
Pasha.

**Comment by timja** [comment]
What permissions are set-up for your Azure AD application?
Anything special about your user account? Are you a guest user?

**Comment by ep4sh** [comment]
Hi @timja 
Tim, I have full (admin) permissions in Jenkins and am able to run any job

REST API (curl request) works well if I would add myself explicitly to the  Azure Active Directory Matrix-based security:

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/19505042/133058046-ee68bd6e-002b-4995-8ebd-c46d3673cc20.png">

**Comment by timja** [comment]
The important part is what permissions does you Azure AD application have?

https://github.com/jenkinsci/azure-ad-plugin#setup-azure-ad-permissions-optional-but-recommended

Group.ReadAll?

**Comment by ep4sh** [comment]
Thank you very much, Tim.  This setting helped to solve the issue.

**Comment by ep4sh** [comment]
Deeply apologize, it looks like I was too hurry when checked this and forget to delete my explicitly added entry in AzureAD Matrix.
Still facing the same issue, but double-checked all settings in AzureAD according to the:
https://github.com/jenkinsci/azure-ad-plugin#setup-azure-ad-permissions-optional-but-recommended
We've checked logs on the AzureAD side - there are no errors.

@timja Tim could you please guide me please which logger we can enable in Jenkins to catch the issue?

**Comment by timja** [comment]
I don't think there's any useful loggers.

I normally set it up locally and use a debugger to pause and see what was returned for the user

**Comment by timja** [comment]
I can't reproduce this =/

I set it up and it works for me.

I have a security group called `Jenkins Read`

Which has Overall/Read and Job/Read permissions.

My 'AlexW' test user works fine:

I did find a separate bug where 'guest' users aren't found, is yours a guest account or a regular user account?

```
curl -u 'AlexW@timja2.onmicrosoft.com:*****' http://localhost:6322/jenkins/whoAmI/api/json
{"_class":"hudson.security.WhoAmI","anonymous":false,"authenticated":true,"authorities":["Jenkins Read","c6fbe770-88ad-445c-8eef-42cda96d9bf1","timja2","adf71a9a-f119-4caf-acfb-d3f7c9b81387","authenticated","92cfffe5-c7b6-4be3-8dc6-e7fd085c9447"],"name":"AlexW@timja2.onmicrosoft.com"}%
➜  azure-ad-plugin git:(feature/proxy-support) ✗
```

**Comment by ep4sh** [comment]
Hi Tim,
thank you very much for your investigations.

During the log analyze we've figured out that the current user becoming "authenticated":
```
Request authenticated as UsernamePasswordAuthenticationToken [Principal=<MY_USERNAME@host.com>, Credentials=[PROTECTED], Authenticated=true, Details=null, Granted Authorities=[authenticated]] by jenkins.security.BasicHeaderApiTokenAuthenticator@7e60bb66
</job/devops/job/Core/job/aws-worker-1/job/Tools-test/build, accessDenied, hudson.model.Hudson@6c191cab> -> null
```

But still have no luck with the setup using the azure group. I assume it depends only on our configuration specific. 
I was able to apply a small workaround (by granting permissions to the authenticated users). I think it's for us.

Wish you everything the best @timja !

Cheerz,
Pasha
