### ISSUE TITLE
Not able to add users in Azure Active Directory Matrix-based security

### ISSUE THREAD

**Issue by andreih89** [jenkinsci/azure-ad-plugin#174]
Jenkins pluglins list :
Common API for Blue Ocean (blueocean-commons): 1.25.1
SCM API Plugin (scm-api): 2.6.5
Script Security Plugin (script-security): 1.78
JavaScript GUI Lib: Moment.js bundle plugin (momentjs): 1.1.1
Trilead API Plugin (trilead-api): 1.0.13
Blue Ocean Pipeline Editor (blueocean-pipeline-editor): 1.25.1
Generic Webhook Trigger Plugin (generic-webhook-trigger): 1.77
Pipeline: AWS Steps (pipeline-aws): 1.43
Design Language (jenkins-design-language): 1.25.1
Docker API Plugin (docker-java-api): 3.1.5.2
Snakeyaml API Plugin (snakeyaml-api): 1.29.1
Web for Blue Ocean (blueocean-web): 1.25.1
Docker Commons Plugin (docker-commons): 1.17
Git Pipeline for Blue Ocean (blueocean-git-pipeline): 1.25.1
Pub-Sub "light" Bus (pubsub-light): 1.16
Role-based Authorization Strategy (role-strategy): 3.2.0
Azure Credentials (azure-credentials): 198.vf9c2fdfde55c
Pipeline implementation for Blue Ocean (blueocean-pipeline-api-impl): 1.25.1
bouncycastle API Plugin (bouncycastle-api): 2.25
Pipeline Graph Analysis Plugin (pipeline-graph-analysis): 1.11
Durable Task Plugin (durable-task): 1.39
JUnit Plugin (junit): 1.53
Bootstrap 5 API Plugin (bootstrap5-api): 5.1.1-1
Docker Pipeline (docker-workflow): 1.26
Slack Notification Plugin (slack): 2.48
Lockable Resources plugin (lockable-resources): 2.12
JaCoCo plugin (jacoco): 3.3.0
i18n for Blue Ocean (blueocean-i18n): 1.25.1
HTML Publisher plugin (htmlpublisher): 1.25
Pipeline: Basic Steps (workflow-basic-steps): 2.24
CloudBees AWS Credentials Plugin (aws-credentials): 1.32
JSch dependency plugin (jsch): 0.1.55.2
Pipeline: REST API Plugin (pipeline-rest-api): 2.19
Pipeline: API (workflow-api): 2.47
Autofavorite for Blue Ocean (blueocean-autofavorite): 1.2.4
Pipeline: Shared Groovy Libraries (workflow-cps-global-lib): 2.21
Azure Commons Plugin (azure-commons): 1.1.3
REST Implementation for Blue Ocean (blueocean-rest-impl): 1.25.1
Pipeline: Stage View Plugin (pipeline-stage-view): 2.19
JAXB plugin (jaxb): 2.3.0
Azure SDK API Plugin (azure-sdk): 61.v6a8af1f5f5b6
JUnit Attachments Plugin (junit-attachments): 1.7
Pipeline Utility Steps (pipeline-utility-steps): 2.10.0
Azure Container Registry Tasks Plugin (azure-container-registry-tasks): 0.6.5
Amazon Web Services SDK :: Logs (aws-java-sdk-logs): 1.12.89-292.v2712528e879c
Matrix Authorization Strategy Plugin (matrix-auth): 2.6.8
GitHub Pipeline for Blue Ocean (blueocean-github-pipeline): 1.25.1
Amazon Web Services SDK :: SSM (aws-java-sdk-ssm): 1.12.89-292.v2712528e879c
Server Sent Events (SSE) Gateway Plugin (sse-gateway): 1.24
Resource Disposer Plugin (resource-disposer): 0.16
Kubernetes CLI Plugin (kubernetes-cli): 1.10.3
Docker plugin (docker-plugin): 1.2.3
Amazon Web Services SDK :: ECR (aws-java-sdk-ecr): 1.12.89-292.v2712528e879c
NodeJS Plugin (nodejs): 1.4.1
Java JSON Web Token (JJWT) Plugin (jjwt-api): 0.11.2-9.c8b45b8bb173
Azure Key Vault Plugin (azure-keyvault): 129.vb7a46bc7b588
GitHub Integration Plugin (github-pullrequest): 0.3.0
Display URL for Blue Ocean (blueocean-display-url): 2.4.1
Pipeline: Nodes and Processes (workflow-durable-task-step): 2.39
Bootstrap 4 API Plugin (bootstrap4-api): 4.6.0-3
ECharts API Plugin (echarts-api): 5.2.1-2
OWASP Markup Formatter Plugin (antisamy-markup-formatter): 2.4
Branch API Plugin (branch-api): 2.7.0
MapDB API Plugin (mapdb-api): 1.0.9.0
Kubernetes Client API Plugin (kubernetes-client-api): 5.4.1
SSH Build Agents plugin (ssh-slaves): 1.31.5
Metrics Plugin (metrics): 4.0.2.8
JavaScript GUI Lib: jQuery bundles (jQuery and jQuery UI) plugin (jquery-detached): 1.2.1
Google OAuth Credentials plugin (google-oauth-plugin): 1.0.6
Caffeine API Plugin (caffeine-api): 2.9.2-29.v717aac953ff3
H2 API Plugin (h2-api): 1.4.199
GitHub API Plugin (github-api): 1.133
Jira plugin (jira): 3.6
Pipeline: Declarative Extension Points API (pipeline-model-extensions): 1.9.2
GitHub Authentication plugin (github-oauth): 0.34
Plugin Utilities API Plugin (plugin-util-api): 2.5.0
PAM Authentication plugin (pam-auth): 1.6
Blue Ocean (blueocean): 1.25.1
Pipeline: Supporting APIs (workflow-support): 3.8
Personalization for Blue Ocean (blueocean-personalization): 1.25.1
Pipeline: Multibranch (workflow-multibranch): 2.26
LDAP Plugin (ldap): 2.7
Jackson 2 API Plugin (jackson2-api): 2.13.0-230.v59243c64b0a5
Environment Injector Plugin (envinject): 2.4.0
Ivy Plugin (ivy): 2.1
Maven Release Plug-in Plug-in (m2release): 0.16.2
Git client plugin (git-client): 3.9.0
JWT for Blue Ocean (blueocean-jwt): 1.25.1
Javadoc Plugin (javadoc): 1.6
Display URL API (display-url-api): 2.3.5
Bitbucket Server Integration (atlassian-bitbucket-server-integration): 2.1.3
JavaScript GUI Lib: Handlebars bundle plugin (handlebars): 3.0.8
Blue Ocean Core JS (blueocean-core-js): 1.25.1
Amazon Web Services SDK :: IAM (aws-java-sdk-iam): 1.12.89-292.v2712528e879c
Token Macro Plugin (token-macro): 266.v44a80cf277fd
Pipeline Maven Integration Plugin (pipeline-maven): 3.10.0
Pipeline: Job (workflow-job): 2.42
JIRA Integration for Blue Ocean (blueocean-jira): 1.25.1
Maven Integration plugin (maven-plugin): 3.12
Amazon Web Services SDK :: Elastic Beanstalk (aws-java-sdk-elasticbeanstalk): 1.12.89-292.v2712528e879c
Pipeline: Declarative (pipeline-model-definition): 1.9.2
Config File Provider Plugin (config-file-provider): 3.8.1
Folder-based Authorization Strategy (folder-auth): 1.3
GitHub plugin (github): 1.34.1
Artifactory Plugin (artifactory): 3.13.2
Pipeline: Build Step (pipeline-build-step): 2.15
Rebuilder (rebuild): 1.32
Build With Parameters (build-with-parameters): 1.6
jQuery plugin (jquery): 1.12.4-1
Folders Plugin (cloudbees-folder): 6.16
Pipeline: GitHub Groovy Libraries (pipeline-github-lib): 1.0
Bitbucket Pullrequest Builder Plugin (bitbucket-pullrequest-builder): 1.5.0
Popper.js 2 API Plugin (popper2-api): 2.10.2-1
Bitbucket Branch Source Plugin (cloudbees-bitbucket-branch-source): 2.9.11
Popper.js API Plugin (popper-api): 1.16.1-2
Subversion Plug-in (subversion): 2.15.0
SSH Credentials Plugin (ssh-credentials): 1.18.1
Allure Jenkins Plugin (allure-jenkins-plugin): 2.29.0
Amazon Web Services SDK :: CloudFormation (aws-java-sdk-cloudformation): 1.12.89-292.v2712528e879c
AnsiColor (ansicolor): 1.0.0
JavaScript GUI Lib: ACE Editor bundle plugin (ace-editor): 1.1
Events API for Blue Ocean (blueocean-events): 1.25.1
Pipeline: Step API (workflow-step-api): 2.24
Checks API plugin (checks-api): 1.7.2
Amazon Web Services SDK :: EC2 (aws-java-sdk-ec2): 1.12.89-292.v2712528e879c
Amazon Web Services SDK :: Minimal (aws-java-sdk-minimal): 1.12.89-292.v2712528e879c
Apache HttpComponents Client 4.x API Plugin (apache-httpcomponents-client-4-api): 4.5.13-1.0
Release Helper Plugin (release-helper): 1.3.3
Amazon Web Services SDK :: ECS (aws-java-sdk-ecs): 1.12.89-292.v2712528e879c
Pipeline (workflow-aggregator): 2.6
Plain Credentials Plugin (plain-credentials): 1.7
GitHub Branch Source Plugin (github-branch-source): 2.10.4
Email Extension Plugin (email-ext): 2.84
Gradle Plugin (gradle): 1.37.1
Ant Plugin (ant): 1.12
Command Agent Launcher Plugin (command-launcher): 1.6
Build Timestamp Plugin (build-timestamp): 1.0.3
Azure CLI Plugin (azure-cli): 0.9
Kubernetes Credentials Plugin (kubernetes-credentials): 0.9.0
GIT server Plugin (git-server): 1.9
Handy Uri Templates 2.x API Plugin (handy-uri-templates-2-api): 2.1.8-1.0
Font Awesome API Plugin (font-awesome-api): 5.15.4-1
Oracle Java SE Development Kit Installer Plugin (jdk-tool): 1.5
Matrix Project Plugin (matrix-project): 1.18
Dashboard for Blue Ocean (blueocean-dashboard): 1.25.1
Amazon Web Services SDK :: All (aws-java-sdk): 1.12.89-292.v2712528e879c
Pipeline SCM API for Blue Ocean (blueocean-pipeline-scm-api): 1.25.1
Amazon Web Services SDK :: CodeBuild (aws-java-sdk-codebuild): 1.12.89-292.v2712528e879c
Authentication Tokens API Plugin (authentication-tokens): 1.4
Anchore Container Image Scanner Plugin (anchore-container-scanner): 1.0.23
Build Timeout (build-timeout): 1.20
EnvInject API Plugin (envinject-api): 1.7
OAuth Credentials plugin (oauth-credentials): 0.4
SonarQube Scanner for Jenkins (sonar): 2.13.1
Mailer Plugin (mailer): 1.34
Bitbucket Pipeline for Blue Ocean (blueocean-bitbucket-pipeline): 1.25.1
Bitbucket Plugin (bitbucket): 1.1.27
Workspace Cleanup Plugin (ws-cleanup): 0.39
Release Plugin (release): 2.11
Azure AD Plugin (azure-ad): 170.v0a6219442a99
Pipeline: Input Step (pipeline-input-step): 2.12
Pipeline: Groovy (workflow-cps): 2.94
REST API for Blue Ocean (blueocean-rest): 1.25.1
Amazon ECR plugin (amazon-ecr): 1.7
Pipeline: Stage Tags Metadata (pipeline-stage-tags-metadata): 1.9.2
Variant Plugin (variant): 1.4
Credentials Plugin (credentials): 2.6.1
AdoptOpenJDK installer Plugin (adoptopenjdk): 1.4
Credentials Binding Plugin (credentials-binding): 1.27
Mercurial plugin (mercurial): 2.15
Office 365 Connector (Office-365-Connector): 4.15.2
Pipeline: SCM Step (workflow-scm-step): 2.13
JQuery3 API Plugin (jquery3-api): 3.6.0-2
Git plugin (git): 4.8.3
OkHttp Plugin (okhttp-api): 3.14.9
Kubernetes Continuous Deploy Plugin (kubernetes-cd): 2.3.1
Kubernetes plugin (kubernetes): 1.30.5
Config API for Blue Ocean (blueocean-config): 1.25.1
GitHub Pull Request Coverage Status (github-pr-coverage-status): 2.1.1
Pipeline: Milestone Step (pipeline-milestone-step): 1.3.2
Structs Plugin (structs): 1.23
Pipeline: Model API (pipeline-model-api): 1.9.2
Timestamper (timestamper): 1.13
SSH server (sshd): 3.0.3
Favorite (favorite): 2.3.3
Pipeline: Stage Step (pipeline-stage-step): 2.5
PowerShell plugin (powershell): 1.7

What Operating System are you using (both controller, and any agents involved in the problem)?

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"

Reproduction steps
Install latest azure-ad-plugin (currently 170.v0a6219442a99) 1st I tried with 179.vf6841393099e
In  Security -> Azure Active Directory Matrix-based security
In the text box for "Azure User/group to add", type the name of a user and it is just loading or didn't find a match.
I am able to log in via azure ad.
When I add a user in "Test user principal name or object id" it recognizes the user.

I have given to Microsoft Graph all the possible rights.
I took this version of the plugin since it was mentioned in https://github.com/jenkinsci/azure-ad-plugin/issues/146 as working.

Jenkins 2.303.2

Please help me with this.

Thanks,
Andrei

**Comment by timja** [comment]
Check your browser console and server logs

**Comment by andreih89** [comment]
It seems Delegated People read.all permission was missing. I had application  People read.all, delegated people.read but not Delegated People read.all. Thanks

**Comment by ClutchRadio** [comment]
> Check your browser console and server logs

What logs am I looking for? I know this issue is closed, but I am having the same issue as well and I have checked my permissions already.  I do not see any errors in the logs or in the console.  I am able to verify the application with a test user but when I try and add that user in the Matrix permissions it always says "We didn't find any matches"
