### ISSUE TITLE
Do Azure AD groups work?

### ISSUE THREAD

**Issue by fatal-exception** [jenkinsci/azure-ad-plugin#18]
Hi there,

thanks for the great plugin! I am able to enable Azure AD authentication, and I'm also able to list individual user IDs in the Matrix-based security config. However, I am unable to find the right syntax for Azure Groups. I have tried the Group ID copied from Azure console, and also the 'com.microsoft.jenkins.azuread.AzureAdGroup@<some-hex>' that appears in the <JENKINS_URL>/whoAmI screen. 

Are Azure AD Groups currently supported? If so, what is the correct syntax to use them?

Many thanks! :)

**Comment by shantur** [comment]
> 'com.microsoft.jenkins.azuread.AzureAdGroup@' that appears in the <JENKINS_URL>/whoAmI screen.

This will be fixed with #39

**Comment by gavinfish** [comment]
This feature should have been enabled in the latest version. Feel free to reopen it if you encounter any problems.
