### ISSUE TITLE
Introduce "View" permission for agents

### ISSUE THREAD

**Issue by meiswjn** [jenkinsci/azure-ad-plugin#192]
### What feature do you want to see added?

Hey,

First of all, thanks for this plugin - it is very useful!

We have a Jenkins instance used by multiple teams. They bring their own agents and specify their agent by label. Some users are concerned, that other users could find out their "label" and use their build agent.
Would it be possible to limit who is able to see an agent by introducing a "View" permission on the agent configuration?

Thanks!

**Comment by timja** [comment]
This isn't related to the Azure AD plugin.

It just uses what is there.

Please report on https://issues.jenkins.io component core.

Seems a little odd it isn't a thing but possibly there's a reason.

Not sure if this helps at all: https://devops.stackexchange.com/a/12232/10034
