### ISSUE TITLE
I have a need to add a user without using the GUI to log in as that user

### ISSUE THREAD

**Issue by ragedberserker** [jenkinsci/azure-ad-plugin#200]
### What feature do you want to see added?

We manage our jenkins cluster then give API_TOKEN access to various service accounts.

Since moving to this plugin requires the user to be in a user@domain.com all prior users that had an API_TOKEN assigned are no longer working. 

A way to create the user so I can just spin up a new API_TOKEN for them without actually having to log in with that service account would be great.

If you have other things I could try, please let me know.

Thanks.

**Comment by timja** [comment]
You could pre-create the users in Jenkins with the script console and create an API token for them.

(not going to provide a script but it would be possible to write one for it)

**Comment by Shasthri** [comment]
@timja the api token created for the existing users doesn't work if the username doesn't matches the UPN (works until v152)
For example,  We have a user with UPN firstname.lastname@domain.com, but the API token was created by just passing firstname.lastname as the username to the script. Also we used to add the user to the azure auth matrix without any issues (even if that user doesn't exist in Azure AD). But post 152 version this is no more the case (at least it used to work until this version), user/group picker only allows us to add the users which exists in azure AD (when graph API integration is enabled)

**Comment by timja** [comment]
Can you not make it match the UPN?

**Comment by Shasthri** [comment]
yes, we can do that as part of upgrade by **recreating the API token** for the users which are not matching the UPN
