### ISSUE TITLE
Azure AD Plugin 0.3.1 is not available on plugin store while Azure Commons 0.2.7 require it

### ISSUE THREAD

**Issue by eranbibi** [jenkinsci/azure-ad-plugin#22]
Updating Azure Commons to 0.2.7 without the new Azure AD Plugin 0.3.1 causing the Jenkins login to be broken. due to this update I found myself locked. had to remove the security and downgrade the Azure Commons to 0.2.6
You should make sure the availability of Azure AD Plugin 0.3.1 on Jenkins Plugin store. and add note about the dependency between those plugins.

**Comment by gavinfish** [comment]
Sorry for your inconvenience. We will pay attention to it next time. Thanks for your suggestion.
