### ISSUE TITLE
Authentication error using Jenkins API Token

### ISSUE THREAD

**Issue by ricemery** [jenkinsci/azure-ad-plugin#27]
Hello,

I am unable to successfully POST to the Jenkins API using a token. This was working until recently. The system is on Jenkins version 2.138.2 and azure-ad-plugin version 0.3.1 .

The error that gets returned over HTTP is:

 
>  java.lang.IllegalStateException: Unexpected authentication type:  org.acegisecurity.providers.UsernamePasswordAuthenticationToken@55752753: Username: myuser; Password: [PROTECTED]; Authenticated: false; Details: org.acegisecurity.ui.WebAuthenticationDetails@0: RemoteIpAddress: 176.16.0.200; SessionId: null; Not granted any authorities
	at com.microsoft.jenkins.azuread.AzureSecurityRealm$3.authenticate(AzureSecurityRealm.java:267)
	at jenkins.security.BasicHeaderRealPasswordAuthenticator.authenticate(BasicHeaderRealPasswordAuthenticator.java:56)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:79)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)

Looking at AzureSecurityRealm line 267 reveals that the code is expecting a AzureAuthenticationToken. But, a org.acegisecurity.providers.UsernamePasswordAuthenticationToken is passed in as the Authentication object. Thus an exception is thrown.

Do you have any suggestions? Reading through open issues (#16) I was curious if maybe the problem had something to do with UPN changes. I have tried using both the User object ID and UPN. The same error is returned regardless of how the user is passed.

Any suggestions would be appreciated.

**Comment by gavinfish** [comment]
Hi @ricemery , sorry for the late response.
Yes, the #16 issue causes some problems here. The workaround here now is add a user with `name(UPN)` in the authorization matrix. Do not delete the origin one. Then use the UPN to have a try.

**Comment by ricemery** [comment]
Hello @gavinfish,
I have not been able to make this work.

As an example.
Lets say I have a user in Active Directory
Username: Foo Bar
Email Addr: foo.bar@company.com
OID: 1234

I have try a bunch of combinations in the authorization matrix
* Foo Bar (1234)
* Foo Bar (foo.bar@company.com)
* Foo Bar (foo.bar)
* Foo Bar(foo.bar@company.com)
* foo.bar
* foo.bar@company.com
* foo.bar@company.com (1234)

In every case I get the same error -
java.lang.IllegalStateException: Unexpected authentication type: org.acegisecurity.providers.UsernamePasswordAuthenticationToken@55752753: Username: foo.bar; Password: [PROTECTED]; Authenticated: false;


I am testing using curl 

curl -k -u "foo.bar:token" https://jenkinsurl

And also testing using Gitlab's integration feature using a URL

https://foo.bar.token@jenkinsurl

I notice that it does not matter if I use an invalid token. The same error is received.

Note that I setup multiple users in the authorization matrix. But, there is a single user under the "/asynchPeople" URL. The user looks like

User ID - foo.bar@company.com
Name  - Foo Bar
Description includes the "Object ID".

Thanks!

**Comment by gavinfish** [comment]
Hi @ricemery ,
In your case, I think with the following items is ok.
* Foo Bar (1234)
* Foo Bar (foo.bar@company.com)

And you should use command like curl -k -u "foo.bar@company.com:token" https://jenkinsurl

**Comment by ricemery** [comment]
Thanks!

I was able to use curl to have jenkins start a pipeline job. Using this format 

curl -k -X POST -u "foo.bar@company.com:token" https://jenkinsurl

Thanks

**Comment by MikhailTymchukDX** [comment]
Still experiencing the same error using the above items format foo.bar@company.com and curl command with -x POST.
Jenkins 2.187 and Azure AD Plugin 1.0.0.
Any thoughts?

**Comment by gavinfish** [comment]
@MikhailTymchukDX What is in your authorization matrix? You need proper matrix content to make it work.

**Comment by MikhailTymchukDX** [comment]
I have full access, like so:
![image](https://user-images.githubusercontent.com/17080984/63248478-0951eb00-c270-11e9-9fec-201e5b8b9918.png)

It works as expected when I using Jenkins web interface.

**Comment by gavinfish** [comment]
@MikhailTymchukDX you need to set the `user/group` like `foo (foo.bar@company.com)`

**Comment by MikhailTymchukDX** [comment]
@gavinfish Do you mean any literal `foo` following an email `foo.bar@company.com` inside the braces format? I thought plain email was enough.

**Comment by gavinfish** [comment]
@MikhailTymchukDX please refer to the README file for more about the configuration of this plugin, thanks.
