### ISSUE TITLE
AAD matrix-based security auto-completion

### ISSUE THREAD

**Issue by gavinfish** [jenkinsci/azure-ad-plugin#28]
Issue #16 changes the Jenkins user id from object id to UPN. This change causes AAD matrix-based security auto-completion providing invalid contents. And this will lead Jenkins API call fails for some cases. Some steps need to fix this:

- [x] use UPN as principal
- [ ] use different sdk to fetch UPN for auto-completion
- [ ] release a new version with block changes

**Comment by shantur** [comment]
@gavinfish : I re-implemented #16 in #39 without breaking current config
