### ISSUE TITLE
Do azure ad plugin support Jenkins config as code?

### ISSUE THREAD

**Issue by TomH54321** [jenkinsci/azure-ad-plugin#293]
### What feature do you want to see added?

Do azure ad plugin support Jenkins config as code?

**Comment by timja** [comment]
Yes see https://github.com/jenkinsci/azure-ad-plugin/blob/master/src/test/resources/com/microsoft/jenkins/azuread/integrations/casc/configuration-as-code.yml

or configure it and export it

**Comment by TomH54321** [comment]
Thank you very much, that is perfect and exactly what I need ^^
