### ISSUE TITLE
Role Strategy not user-friendly when using Groups

### ISSUE THREAD

**Issue by anonfriese** [jenkinsci/azure-ad-plugin#30]
When using the provided Azure Active Directory Matrix-based security it's possible to use AD Groups using their respective Name. The Plugin seems to resolve their Object ID from Azure.

Unfortunately the Matrix-based Security is not able to meet my needs and I would like to use the Role Strategy Plugin instead. Unfortunately this is not tied to Azure AD, thus the AD Group Resolution by Name is not working.

Is there a specific Reason the AD Plugin needs to implement it's own Strategy? Would be great if Group Names could be resolved independently of the Authorization Strategy or at least a "Azure Active Directory Role-based Security" Mode could be implemented.

**Comment by shantur** [comment]
@anonfriese 
I had the same issue and thats what i fixed in #39

**Comment by gavinfish** [comment]
Thanks for @shantur to fix this, closing.
