### ISSUE TITLE
Can't extract id_token

### ISSUE THREAD

**Issue by xionglingfeng** [jenkinsci/azure-ad-plugin#32]
I followed [this](https://wiki.jenkins.io/display/JENKINS/Azure+AD+Plugin) tutorial configured my Jenkins installation.
When user clicked 'Log in' in Jenkins, they are correctly redirected to Office 365 login page. However, when they redirected back to Jenkins, an exception thrown. The URL looks like:
> https://jenkins.xxxxxxx.com/securityRealm/finishLogin

The exception description:
> java.lang.IllegalStateException: Can't extract id_token
> 	at com.microsoft.jenkins.azuread.AzureSecurityRealm.doFinishLogin(AzureSecurityRealm.java:199)
> 	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
> 	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
> 	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
> 	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
> 	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:130)
> 	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
> 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
> Caused: javax.servlet.ServletException
> 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:789)
> 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
> 	at org.kohsuke.stapler.MetaClass$3.doDispatch(MetaClass.java:212)
> 	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
> 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
> 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
> 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
> 	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
> 	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
> 	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
> 	at com.microsoft.jenkins.azuread.AzureSecurityRealm$CrumbExempt.process(AzureSecurityRealm.java:343)
> 	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:73)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
> 	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
> 	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
> 	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
> 	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
> 	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
> 	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
> 	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
> 	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
> 	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
> 	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
> 	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
> 	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
> 	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:503)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
> 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
> 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by gavinfish** [comment]
@xionglingfeng ,

I think your issues is similar with #12 .

**Comment by xionglingfeng** [comment]
@gavinfish That's correct. This issue is similar (to same) as #12. However, #12 does not has any working solutions, and @jaypharis answer is not relevant.
I looked into the post data send to reply URL, and realize this is an AAD configuration issue. AAD returned an error instead of a normal response, which is described [https://docs.microsoft.com/en-us/skype-sdk/websdk/docs/troubleshooting/auth/aadauth-enableimplicitoauth](here).

Solution: Log in to Azure AD Portal, find `App registration (Preview)`, select the jenkins application. In `Authentication` page, select `ID tokens` under `Implicit grant`.

Suggestions: it is better for this plugin to validate the response passed to `finishLogin` and correctly show the error messages (if AAD returns any errors).

**Comment by VireshDoshi** [comment]
> @gavinfish That's correct. This issue is similar (to same) as #12. However, #12 does not has any working solutions, and @jaypharis answer is not relevant.
> I looked into the post data send to `finshLogin` and realize this is an AAD configuration issue. AAD returned an error instead of a normal response, which is described [here](https://docs.microsoft.com/en-us/skype-sdk/websdk/docs/troubleshooting/auth/aadauth-enableimplicitoauth).
> 
> Solution: Log in to Azure AD Portal, find `App registration (Preview)`, select the jenkins application. In `Authentication` page, select `ID tokens` under `Implicit grant`.
> 
> Suggestions: it is better for this plugin to validate the response passed to `finishLogin` and correctly show the error messages (if AAD returns any errors).

Yep, this worked for me :-)

**Comment by Oxymoron290** [comment]
Enabling the implicit grant on ID tokens solved this problem for me as well

**Comment by robertzakrocki** [comment]
Thanks @xionglingfeng Enabling the implicit grant on ID tokens solved this problem for me as well ;)
