### ISSUE TITLE
Upgrading to latest LTS version (2.150.2) causes endless authorization loop

### ISSUE THREAD

**Issue by aglorei** [jenkinsci/azure-ad-plugin#34]
I have several clusters in kubernetes using the alpine image tags that have been sitting at 2.150.1 for a while (i.e., tag `2.150.1-alpine`). Today, the LTS pointer moved to 2.150.2, largely as a means to address various SECURITY tickets having to do with authentication (see https://jenkins.io/security/advisory/2019-01-16/). After upgrading each cluster to this new image (`2.150.2-alpine`), the initial authentication of into the cluster using my Azure AD credentials forces a loop at Azure's login.microsoftonline.com page, and the following logs into stdout from the container:
```
Jan 16, 2019 7:05:44 PM com.microsoft.jenkins.azuread.AzureSecurityRealm doFinishLogin
INFO: Requesting oauth code time = 351684 ms
Jan 16, 2019 7:05:56 PM com.microsoft.jenkins.azuread.AzureSecurityRealm doFinishLogin
INFO: Requesting oauth code time = 11450 ms
Jan 16, 2019 7:06:02 PM com.microsoft.jenkins.azuread.AzureSecurityRealm doFinishLogin
INFO: Requesting oauth code time = 5397 ms
Jan 16, 2019 7:06:04 PM com.microsoft.jenkins.azuread.AzureSecurityRealm doFinishLogin
INFO: Requesting oauth code time = 2694 ms
```
This happens without ever getting to the Jenkins dashboard splash. I've verified that this problem is persistent with the debian image (tag `2.150.2`) and can be addressed by reverting back to the 2.150.1 tags.

**Comment by tillig** [comment]
I ran into this, too, and thought there was some sort of configuration mismatch or cookie cached on my side or something. Nope. 2.154 doesn't have this problem, 2.160 does. I also verified 2.150.2 has the infinite redirect and 2.150.1 doesn't.

**Comment by gavinfish** [comment]
Do you have tried to clean up the cookies for the Jenkins server or access to it in an incognito window?

**Comment by tillig** [comment]
Yup. I even flushed and reset my entire browser, cookies, cache, the whole bit, just to be sure.

**Comment by petermylemans** [comment]
Same here: we downgraded back to 2.150.1.

**Comment by ratherDashing** [comment]
Same experience here.  If anyone is looking for the 2.150.1 deb it is here:

http://pkg.jenkins.io/debian-stable/binary/jenkins_2.150.1_all.deb

as people have mentioned, downloading that package and doing a "dpkg -i" on it resolved this issue but we are now exposed to the security vulnerabilities mentioned:

https://jenkins.io/security/advisory/2019-01-16/

**Comment by MSLaguana** [comment]
We also ran into this same situation and had to downgrade back to 2.150.1 until this is fixed.

**Comment by gavinfish** [comment]
Hi all, I have created a PR #35  to fix this, I will make an urgent release soon. Sorry for all your inconvenience.

**Comment by gavinfish** [comment]
Version 0.3.2 has been released. It should be soon available in the Jenkins plugin manager.

**Comment by Wadeck** [comment]
@gavinfish Great job and especially the quick reaction. We cause such regression due to the User Seed new feature that was provided to correct some vulnerabilities in the core.

**Comment by ratherDashing** [comment]
I can confirm this fixed our issue.  We are now running the 2.150.2 with no Azure issues.  Thank you!
