### ISSUE TITLE
Graph API calls for jobs which return 404

### ISSUE THREAD

**Issue by mo-saeed** [jenkinsci/azure-ad-plugin#358]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.375.1
OS: Linux - 4.15.0-1113-azure
---
azure-ad:303.va_91ef20ee49f
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

OS: Linux

### Reproduction steps

We are seeing in the logs the following errors 

jenkins[9758]: GET https://graph.microsoft.com/v1.0/users/Const%20ord
jenkins[9758]: SdkVersion : graph-java/v5.41.0
jenkins[9758]: 404 : Not Found
jenkins[9758]: [...]
```
Const/ord is not a user it's just Folder/job so I am wondering why it tries to check a folder job as a user in azure AD

would appreciate your input and if we have something wrong in our configurations

### Expected Results

no 404 errors for checking jobs in azure active directory

### Actual Results

got alot of 404 for jenkins jobs with not found users in azure AD

### Anything else?

_No response_

**Comment by timja** [comment]
can you provide more clear steps to reproduce please? what are you doing when you trigger the logs?

**Comment by mo-saeed** [comment]
I am not really how to reproduce this or what actually trigger this behanvior

**Comment by timja** [comment]
Not going to be able to help without clear reproduction steps from scratch.

**Comment by timja** [comment]
If you can provide steps to reproduce I'll happily re-open it or you can submit a new one.

**Comment by mo-saeed** [comment]
did you get what I said? I asked to keep it open so maybe somebody else is able to help identify what could trigger such behavior. the issue itself to understand what triggers this behavior not how to fix it based on reproduction steps. so in short I need some theories based on how this plugin works and what could cause these triggers.

**Comment by timja** [comment]
It _could be_ something to do with Project based security and azure ad matrix authorization strategy when someone configures a job.

If you use features like that it would be a starting point to see if the logs trigger when you configure the job
