### ISSUE TITLE
No longer able to add users in matrix-based security mode

### ISSUE THREAD

**Issue by ffloimair** [jenkinsci/azure-ad-plugin#362]
After updating to the latest Jenkins LTS Release (2.375.2 from 2.375.1) along with the latest version of the plugin it is no longer possible to add new users. The input field where the name or e-mail address can be entered is no longer visible, only the add button is there but it doesn't do anything if I can't search for users or enter a complete e-mail before hand.

<img width="209" alt="image" src="https://user-images.githubusercontent.com/6363261/212077315-22999756-0891-4a26-aa8a-0daf9a20be53.png">

Not sure if this is an incompatibility of the plugin with the latest Jenkins LTS version or a problem of the plugin itself. Downgrading the plugin to a previously working version (303) did not change anything.

Jenkins version: 2.375.2
Plugin version: 308.v10a_6e24f30b_4

**Comment by timja** [comment]
Works just fine for me, is there any errors in the console?

Are you missing the input box for it?

<img width="235" alt="image" src="https://user-images.githubusercontent.com/21194782/212096637-afcc5cb7-4d68-457a-9554-74d54344ef6b.png">

**Comment by ffloimair** [comment]
Yes exactly, the input box is not showing.

**Comment by timja** [comment]
check your browser console and server logs please

**Comment by ffloimair** [comment]
The console does show an error though:
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-mock-provider" has already been used with this registry
    at https://jenkins.mydomain/plugin/azure-ad/js/azure-ad-bundle.js:2:52051
    at https://jenkins.mydomain/plugin/azure-ad/js/azure-ad-bundle.js:2:52066
    at Co (https://jenkins.mydomain/plugin/azure-ad/js/azure-ad-bundle.js:6:8922)
    at https://jenkins.mydomain/plugin/azure-ad/js/azure-ad-bundle.js:6:9302
    at https://jenkins.mydomain/plugin/azure-ad/js/azure-ad-bundle.js:1730:4304
```

**Comment by ffloimair** [comment]
No error in server logs.
I can see successful fetching of existing users though.

**Comment by timja** [comment]
You tried clearing cache? what browser / version of browser?

**Comment by timja** [comment]
I've cut a new release as well with the latest version of that component but I couldn't reproduce with either version

**Comment by ffloimair** [comment]
Yeah, clearing cache doesn't change anything. Tried with Chrome 109, Edge 108 and Firefox 108.
Result is the same everywhere.

**Comment by ffloimair** [comment]
The problem is fixed with version 313 of the plugin. Just installed it and everything works fine.
Thanks!
