### ISSUE TITLE
Unable to properly authenticate on jenkins 2.150.2

### ISSUE THREAD

**Issue by tomecho** [jenkinsci/azure-ad-plugin#37]
When I updated our jenkins server to the latest version of 2.150.2, I was unable to login to jenkins upon visiting our jenkins server by browsing to the normal url I was directed to sign in, after signing in I was sent to jenkins /relms/finishLogin (or something like that) which directed me right back to the microsoft sign in url creating a loop between the two points.

Azure ad plugin was left at 0.3.1 the entire time.

related to https://issues.jenkins-ci.org/browse/JENKINS-55654 but im not sure if this is jenkins itself or the plugin

**Comment by gavinfish** [comment]
Hi @tomecho , I think this issue is duplicate with #34 and it has been fixed. Please upgrade to the latest version of Azure ad plugin and have a try, thanks.
