### ISSUE TITLE
Teams view needs to use Object IDs instead of friendly names

### ISSUE THREAD

**Issue by EricBartusch** [jenkinsci/azure-ad-plugin#38]
I'm using Cloudbees Core and the new Teams view.  In order to make use of the users in Azure AD, I need to specify the Object IDs instead of the friendly Group name/Name in AD.

![image](https://user-images.githubusercontent.com/28985923/52882563-b9159700-312d-11e9-8090-74d0ea562b0b.png)

Related to #30

**Comment by EricBartusch** [comment]
Oddly enough, on the Jenkins Operations Center, my user configure page is linked to via my Unique Principal Name, but on the Managed Masters connected to the OC, it's the Object ID again.

**Comment by gavinfish** [comment]
I think Cloudbees Core Teams view uses different interfaces from the Jenkins.

**Comment by gavinfish** [comment]
This fix has been released, feel free to reopen it if there are any other questions.
