### ISSUE TITLE
How to get UPN from an Azure AD UID?

### ISSUE THREAD

**Issue by wolfmah** [jenkinsci/azure-ad-plugin#397]
### Describe your use-case which is not covered by existing documentation.

I recently upgrade to the latest LTS (2.387.1) and I upgrade the plugin azure-ad to version 336.vd05b_01358644.

As stated in the release notes, there are breaking changes regarding what kind of user ID is returned/used by the plugin. Before, it was the UPN (email address), now it's the UID.

This cause me problem since I was using the UPN returned by the [input step](﻿﻿https://www.jenkins.io/doc/pipeline/steps/pipeline-input-step) to know which user was giving the process it's approval. I was using that returned value to match against an external list. Now, since the UID is not something that is known to my external list, my pipeline is no longer working.

Of course, reverting the plugin fix the issue, but is not ideal long term.

My question: in Jenkins, is there a way to get the UPN when presented with an Azure AD UID?

Thanks,
wolfmah

**Comment by timja** [comment]
This should do it:

```
sh script: "az ad user show --id $OBJECT_ID", returnStdout: true
```

**Comment by TobiX** [comment]
I don't know when you need the user details, but https://plugins.jenkins.io/build-user-vars-plugin/ still works fine for me: `BUILD_USER_EMAIL` contains the user's maill in a running pipeline
