### ISSUE TITLE
Azure plugin retirement does not consider Azure AD authentication for Jenkins itself

### ISSUE THREAD

**Issue by ffloimair** [jenkinsci/azure-ad-plugin#400]
### What feature do you want to see added?

While not exactly a feature request, I do request though to consider the following which is not covered by your current retirement strategy.

I got the e-mail today from Azure telling me that Jenkins plug-ins for Azure will be retired.
It states
> Because the Azure command-line interface (Azure CLI) provides a more up-to-date and robust experience when accessing Azure Services, we will retire Jenkins plug-ins for Azure on 29 February 2024.

This sounds reasonable to me as far as build steps in Jenkins pipelines are concerned.
However Azure CLI cannot cover a major use case that would then no longer be possible:

**Login with Azure AD User to Jenkins itself**, which is currently covered by the _Azure AD plugin_.

I therefore strongly urge you to reconsider NOT retiring this plugin or to provide a well-documented alternative so that this use case is covered. As of today there is nothing in the documentation that would enable current users of this plugin to still have such functionality.

**Comment by timja** [comment]
Ignore the email from Microsoft. They haven’t developed these plugins in a long time. We were supposed to co-maintain these for a period but they did absolutely nothing… not even sponsor Azure cloud costs…

**Comment by ffloimair** [comment]
OK, got it. Thanks for the information. Seemed to me as if they were in the lead here and decided to do nothing.

**Comment by timja** [comment]
@NotMyFault why did you add the topic to this repository?

![image](https://github.com/jenkinsci/azure-ad-plugin/assets/21194782/093f77f1-ef68-4718-946d-e632b5841929)

**Comment by NotMyFault** [comment]
> @NotMyFault why did you add the topic to this repository?
> 
> ![image](https://user-images.githubusercontent.com/21194782/260428176-093f77f1-ef68-4718-946d-e632b5841929.png)

![Screenshot 2023-08-14 at 12 49 23](https://github.com/jenkinsci/azure-ad-plugin/assets/13383509/b9a99be1-7a4c-42dd-8eed-3be0ebb1ee43)

If the plugin is EOL in ~6 months, this should be communicated timely, or the paragraph should be removed or revised.

**Comment by timja** [comment]
It is not end of life. Microsoft "provides" official paid support for it till then. At that point Microsoft supports ends and it is community only support.

**Comment by NotMyFault** [comment]
> It is not end of life. Microsoft "provides" official paid support for it till then. At that point Microsoft supports ends and it is community only support.

Oic, I didn't read it that way.
