### ISSUE TITLE
Repo is missing topics so plugin is not listed under authentication

### ISSUE THREAD

**Issue by jtnord** [jenkinsci/azure-ad-plugin#412]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

go to https://plugins.jenkins.io/ui/search?sort=relevance&categories=&labels=user&view=Tiles&page=1&query=azure-ad or the plugin manager in Jenkins

search for authentication related plugins

### Expected Results

azure AD pops up

### Actual Results

azure-ad is not in the list

### Anything else?

as per https://www.jenkins.io/doc/developer/publishing/documentation/#labeling-plugins

the following topics should be added to this repository `security` and `user`

**Comment by timja** [comment]
Done, user is a very erm generic topic
