### ISSUE TITLE
User's groups info not updating in Jenkins after being added to or removed from groups in Azure AD

### ISSUE THREAD

**Issue by zkzqzk** [jenkinsci/azure-ad-plugin#413]
For example, when a user login the first time, Jenkins gets all the group info for that user. But  when the user is added to a new group in Azure AD later.  The user in Jenkins does not have this new group.

I am not sure if this is a misconfiguration, bug or just the plugin doesn't have this feature at this stage?

**Comment by timja** [comment]
You would need to provide more information.

Is the user logging in again as the groups should be reloaded then.
What's not working?

Explain step by step how to reproduce and I can give a better view / possibly look at it
