### ISSUE TITLE
Insufficient privileges error

### ISSUE THREAD

**Issue by spijs** [jenkinsci/azure-ad-plugin#42]
I've followed the instructions to setup the plugin, but I keep getting the error that I do not have sufficient privileges. 
`com.microsoft.azure.management.graphrbac.GraphErrorException: Status code 403, {"odata.error":{"code":"Authorization_RequestDenied","message":{"lang":"en","value":"Insufficient privileges to complete the operation."}`
The instructions mention setting 'Windows Azure Active Directory Read directory access' so I went on and enabled the closest I could find  which is the `Graph Directory.ReadWrite.All` and `Directory.ReadAll`. This still didn't work so I went on and enabled basically all of the graph permissions. I also made sure I granted admin consent in App Registrations.

What am I doing wrong? + Potentially an update to the readme is required.

**Comment by gavinfish** [comment]
AAD app registrations has released a new version which make the difference here. From my working settings, it should need below permissions. Also #41 will make these permissions not necessary.
![aad](https://user-images.githubusercontent.com/6169722/57279005-83ec6580-70da-11e9-8aeb-6cc385593753.png)
