### ISSUE TITLE
Settings 'verified', can't login 

### ISSUE THREAD

**Issue by lesterp33** [jenkinsci/azure-ad-plugin#44]
After following the setup in the README and creating/adding my Client ID, Client Secret, and Tenant in the Azure Active Directory security config page in Jenkins, I get a 'Successfully verified' message after clicking the 'Verify Application' button.

However, when attempting to log in, after selecting my credentials, I get the following exception:
AADSTS900384: JWT token failed signature validation [Reason - The key was not found., Thumbprint of key used by client: 

I've followed the README along with steps from here:
http://cloud.badalkotecha.com/2018/09/jenkins-role-based-access-control-rbac-with-azure-ad-step-by-step.html

But still am having the same issue at login.  I feel like I'm missing a basic permission or config somewhere.

**Comment by gavinfish** [comment]
Following the plugin's main page https://plugins.jenkins.io/azure-ad should work. Which version do you use? How you do host your Jenkins server?

**Comment by lesterp33** [comment]
Using the latest version of the plugin, 0.3.4, with Jenkins 2.150.3 LTS.  Jenkins is hosted on-prem, running in a container, behind nginx for https.

**Comment by timja** [comment]
Plugin was re-worked for 1.0 closing old issues
