### ISSUE TITLE
Can't make it work - Insufficient privileges to complete the operation

### ISSUE THREAD

**Issue by Pistahh** [jenkinsci/azure-ad-plugin#46]
Hi,

sorry for the vague information, I can provide more details if needed.

I cannot make Azure auth work - I get the "Insufficient privileges to complete the operation" error message whatever I try.

A couple of months ago I set up a test instance, following the plugin instructions and it works properly. A couple of days ago I tried to create a staging server but it doesn't work. What I see is that meanwhile Azure app registrations changed and the plugin (0.3.4) instructions don't follow the changes anymore. I still set up all the same permissions for the new app as I have for the old working app, but it still doesn't work.
The Jenkins URL is https and the one in Jenkins config matches the one in App Registrations
Verifying the Azure settings in Jenkins config comes back with "Succeeded".
The registration including API permissions for the new server match the permissions for the old server (the only difference is the fqdn in the URL). Still it doesn't work.

 Is 0.3.4 expected to work with the new App Registrations? When will the new version of the plugin be released?

Thanks,
Istvan

**Comment by gavinfish** [comment]
The new App Registrations is different from the previous one. I put some details about the permission in the new version at #42 . The new version will be released after the PR #45 being merged.

**Comment by Pistahh** [comment]
Using these details I could configure it correctly. One mistake I made was that initially I set up "Delegated" permission for Directory.Read.All, instead of "Application" type.

These are the permissions needed:

![image](https://user-images.githubusercontent.com/9561441/59766197-8922ff80-9297-11e9-9ce8-e3e6db4a0b32.png)
