### ISSUE TITLE
Add documentation and tests for using this plugin with job-dsl

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-ad-plugin#467]
### What feature do you want to see added?

.

**Comment by ieugen** [comment]
As I commented in https://github.com/jenkinsci/azure-ad-plugin/pull/466#issuecomment-1695908081 (after it was closed), 
I can't make the plugin to work with folder. 

My configuration 
```
        folder('DS') {
           properties {
               azureAdAuthorizationMatrix {
               entries {
                group {
                    name('DsUsers')
                    permissions(['Job/Build',
                    'Job/Configure',
                    'Job/Delete',
                    'Job/Read',
                    'Job/Cancel'])
                }}
            }
           }
```

throws error:

```
javaposse.jobdsl.plugin.structs.ParameterMissingException: No signature of method: entries() is applicable for argument types: (script$_run_closure1$_closure2$_closure4$_closure5) values: [script$_run_closure1$_closure2$_closure4$_closure5@5d0c3f80]
Possible solutions: permissions(), inheritanceStrategy()
```

My goal is to allow members of a specific Azure AD user group access to a folder.
In the case above, I would like to give users from `DsUsers` azure group, permission to manage jobs (run builds) in `DS` folder.

**Comment by timja** [comment]
Try the old format of matrix auth https://github.com/daniel-beck/matrix-auth-plugin/blob/jcasc-type-safety-2/src/test/resources/org/jenkinsci/plugins/matrixauth/integrations/casc/configuration-as-code-v2-ambiguous.yml#L65

(but making sure to include the azureAd prefix on authorizationMatrix)

**Comment by ieugen** [comment]
Hi, I deployed with these:

```
        folder('DS') {
           properties {
               azureAdAuthorizationMatrix {
                permissions([
                'Job/Build:DSUsers',
                'Job/Configure:DSUsers',
                'Job/Delete:DSUsers',
                'Job/Read:DSUsers',
                'Job/Cancel:DSUsers'
                ])}
           }
```

I am glad that it works. 
I do think the new format is simpler to follow and would preferre it - mainly for consistency with the other plugin and easy migration.
