### ISSUE TITLE
Slowness on inital authorization

### ISSUE THREAD

**Issue by EricBartusch** [jenkinsci/azure-ad-plugin#47]
Hi,

When logging into Jenkins for the first time in a while, it will take upwards of 30 seconds to authorize.  I'm wondering if the plugin itself is slow or if it's our Azure AD setup.  Does anyone else see this?

Thanks,
Eric

**Comment by Pistahh** [comment]
I'm seeing this issue too. 

![image](https://user-images.githubusercontent.com/9561441/59765931-0d28b780-9297-11e9-998d-02e4d53a4b01.png)

**Comment by EricBartusch** [comment]
Are you on 1.0.0? I've yet to upgrade and was wondering if it's faster.

**Comment by gavinfish** [comment]
Hi, could you please check your log? There should be something like `INFO: Requesting oauth code time = ** ms`, how long does it take?

**Comment by EricBartusch** [comment]
![image](https://user-images.githubusercontent.com/28985923/59855514-b379c900-933a-11e9-94c8-61040f191cd0.png)

![image](https://user-images.githubusercontent.com/28985923/59855585-dc9a5980-933a-11e9-84c3-7c0bc1315d4f.png)

Similar to Pistahh, I'm seeing the most delay on the finishLogin step of authorization.  The URL in the browser shows a Microsoft domain, so is this on their end as opposed to the plugin or Jenkins?

**Comment by szalapski** [comment]
I am now encountering this several times a day.  What can be done?

**Comment by gavinfish** [comment]
@szalapski How do you host your Jenkins sever, behind nginx? If so, I suggest you could change the nginx setting to mitigate the 504 error temporarily.

**Comment by szalapski** [comment]
As far as I know, we are not using nginx but rather Cloudbees and Openshift.

**Comment by EricBartusch** [comment]
Thank you @gavinfish! The login is much faster now.  Permissions sometimes take a bit to finish due to the async changes, but it's an overall improvement.  Making it async is a good fix for the symptoms of the slowness, but is there any way to make the actual group permission check faster, or is that an issue in Azure AD itself?

**Comment by EricBartusch** [comment]
Unfortunately we've had to roll back to 1.1.0.  Users were experiencing authorization issues. Sometimes when logging in, they'd eventually get their group permissions, and other times the permissions never updated properly. Not sure if the async operations just never came back.

**Comment by snallami** [comment]
Just some thoughts around caching and not sure if it is technically possible.

Is it possible to Cache user permissions upon first login with some sort of configurable cache expiry period ? this way only first login is taxed and subsequent requests within expiry period will be  faster.

**Comment by gavinfish** [comment]
@EricBartusch Thanks for your useful response. And it is true that group permission itself needs to be accelerated, especially for large group org.

For the async operation, there should be error log like "Fail to grant group permission: ***" in Jenkins log.

**Comment by szalapski** [comment]
For what it's worth, this is a problem that our hundreds of users experience now every time they begin using the site after an hour of not using it...for me, it is 2-5 times per day nearly every day.  Thanks for looking into it further.

**Comment by timja** [comment]
I think fixed with caching?
