### ISSUE TITLE
Support for Microsoft Graph API

### ISSUE THREAD

**Issue by spkrishnankutty** [jenkinsci/azure-ad-plugin#53]
Auto populate of groups and users doesn't work on the new Microsoft Graph API with 'Read Directory data'. Verified this by turning on the legacy Azure Active Directory Graph. 

Just wondering if there are plans to support the new graph api.

**Comment by azuroff** [comment]
> You are receiving this message because our reporting indicates one or more of your applications are using Azure AD Graph. Applications will no longer receive responses from the Azure AD Graph endpoint after June 30th, 2022.

We recently received an email from Microsoft letting us know that some of our applications were still using Azure AD Graph and that we need to migrate them to use the Microsoft Graph API instead.  Jenkins (using this plugin) was one of those applications.

Are there plans to migrate the plugin to use the MS Graph API?

**Comment by oolfloo** [comment]
Any updates on this? We're interested in this as well.

**Comment by timja** [comment]
For anyone interested there is a test build here: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/azure-ad/153.vfa95a4ba16c3/azure-ad-153.vfa95a4ba16c3.hpi

Please report any feedback in https://github.com/jenkinsci/azure-ad-plugin/pull/118
