### ISSUE TITLE
Change of Cache Duration does not take any effect

### ISSUE THREAD

**Issue by maikbrauer** [jenkinsci/azure-ad-plugin#530]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.426.2
OS: Linux - 6.1.32-0-virt
Java: 17.0.9 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
authentication-tokens:1.53.v1c90fd9191a_b_
azure-ad:449.v92b_39a_d8e523
azure-sdk:157.v855da_0b_eb_dc2
bouncycastle-api:2.30.1.77-225.v26ea_c9455fd9
branch-api:2.1144.v1425d1c3d5a_7
caffeine-api:3.1.8-133.v17b_1ff2e0599
cloudbees-folder:6.858.v898218f3609d
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-95.v22a_d30ee5d36
configuration-as-code:1670.v564dc8b_982d0
credentials:1311.vcf0a_900b_37c2
credentials-binding:642.v737c34dea_6c2
display-url-api:2.200.vb_9327d658781
durable-task:543.v262f6a_803410
git:5.1.0
git-client:4.6.0
gson-api:2.10.1-15.v0d99f670e0a_7
instance-identity:185.v303dc7c645f9
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.16.1-373.ve709c6871598
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
kubernetes:4029.v5712230ccb_f8
kubernetes-client-api:6.9.2-239.ve49a_3f285167
kubernetes-credentials:0.11
mailer:463.vedf8358e006b_
matrix-auth:3.2.1
metrics:4.2.18-442.v02e107157925
mina-sshd-api-common:2.11.0-86.v836f585d47fa_
mina-sshd-api-core:2.11.0-86.v836f585d47fa_
okhttp-api:4.11.0-157.v6852a_a_fa_ec11
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-groovy-lib:689.veec561a_dee13
pipeline-input-step:477.v339683a_8d55e
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2168.vf921b_4e72c73
pipeline-model-definition:2.2168.vf921b_4e72c73
pipeline-model-extensions:2.2168.vf921b_4e72c73
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2168.vf921b_4e72c73
plain-credentials:143.v1b_df8b_d3b_e48
scm-api:683.vb_16722fb_b_80b_
script-security:1313.v7a_6067dc7087
snakeyaml-api:2.2-111.vc6598e30cc65
ssh-credentials:308.ve4497b_ccd8f4
structs:325.vcb_307d2a_2782
trilead-api:2.133.vfb_8a_7b_9c5dd1
variant:60.v7290fc0eb_b_cd
workflow-aggregator:596.v8c21c963d92d
workflow-api:1283.v99c10937efcb_
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:3837.v305192405b_c0
workflow-durable-task-step:1313.vcb_970b_d2a_fb_3
workflow-job:1385.vb_58b_86ea_fff1
workflow-multibranch:770.v1a_d0708dd1f6
workflow-scm-step:415.v434365564324
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:865.v43e78cc44e0d

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

n/a

### Reproduction steps

Put a Cache Duration of 60 seconds, login and wait 2 Minutes and again try to do something.log

### Expected Results

Session should get terminated and re-auth to be done via Refresh-Token or complete Re-auth via Azure.The session

### Actual Results

You stay logged in all the time. Value change does not influences anything as far as I can see

**Comment by timja** [comment]
The cache isn’t for session it’s for cached data from Entra ID as far as I know.

**Comment by maikbrauer** [comment]
@timja so what does this value in the Plugin influence? So, we know that we get the AccessToken (valid 1 hour as default) and we get a refresh Token, which lifetime we can set also in which time window a new AccessToken can be obtained.

**Comment by timja** [comment]
It's this code here:
https://github.com/jenkinsci/azure-ad-plugin/blob/38225fc388c7b0c46682d9223d5be0a56c2acddd/src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java#L377-L390

basically it caches user details from entra id.
https://github.com/jenkinsci/azure-ad-plugin/blob/38225fc388c7b0c46682d9223d5be0a56c2acddd/src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java#L461-L505

e.g. if someone uses an API token and their group details need looking up, they'll be cached for that duration so multiple API calls don't contact Entra ID
