### ISSUE TITLE
Communicating with the Jenkins API

### ISSUE THREAD

**Issue by philwinder** [jenkinsci/azure-ad-plugin#54]
Hi there,
I am having the same problem as the people in #27 and #24.

As another application (e.g. another web UI), I want to access the jenkins API using the user's AAD credentials. All of our users are in AD in the format `phil.winder@domain.com`.

To test API access, I have been doing the following.

1. In the `Azure Active Directory Matrix-based security` list, we have the ID of an AD group. My user (`phil.winder@domain.com`) has access to the UI.
2. Generate an AD token from the az cli. `az account get-access-token`. Copy the `accessToken` field. Export the token: `export TOKEN=<token>`
3. Use curl to call the API: `curl --insecure -v -u "Phil.Winder@domain.com:$TOKEN" -k https://JENKINS_DNS/api/json`

I receive the error:

```
java.lang.IllegalStateException: Unexpected authentication type: org.acegisecurity.providers.UsernamePasswordAuthenticationToken@c159979b: Username: Phil.Winder@XXXXXX.com; Password: [PROTECTED]; Authenticated: false; Details: org.acegisecurity.ui.WebAuthenticationDetails@ffff6a82: RemoteIpAddress: 10.X.X.X; SessionId: null; Not granted any authorities
	at com.microsoft.jenkins.azuread.AzureSecurityRealm$3.authenticate(AzureSecurityRealm.java:268)
...
```

This is the same error as in #27. So I tried the workarounds in there. I have tried:

- Adding my user through the autocomplete `phil.winder@domain.com (12345-1234...)`.
- `phil.winder@domain.com (phil.winder@domain.com)`
- `12345-1234.. (12345-1234...`

And every combination thereof. Every request results in the same error.

I have confirmed in the Jenkins user list that my UPN and jenkins username (when logging into the UI) is `Phil.Winder@domain.com`

Is there any way to figure out why the AD plugin is receiving a basic `UsernamePasswordAuthenticationToken` type and not the expected `AzureAuthenticationToken`?

It would also help to improve the readme a little. The line at the bottom of https://github.com/jenkinsci/azure-ad-plugin#setup-in-azure-active-directory just says "add your user/group value with pattern userName|groupName (principalName)". What is userName in this context? And what is principalName? Are those AD things? Or jenkins things?

Thanks.

**Comment by gavinfish** [comment]
@philwinder I am afraid you need to generate the token from Jenkins side instead of Azure cli.

**Comment by philwinder** [comment]
Yes, that's it. I had assumed when people had said "token", they meant an AD token.

To generate a token for the API you need to:
1. Go to jenkins -> Users -> your user.
2. Click on configure. Go to the API Token section and generate a new token.

Then curl like this:

```
export TOKEN=12345...
curl --insecure -v -u "phil.winder@domain.com:$TOKEN" -k https://jenkins-url.com/api/json
```

One final question if you don't mind @gavinfish? If I remove the user `phil.winder@domain.com` from the jenkins-authorised AD group, will that revoke API access too? 

For example, imagine the following situation. The token has been generated by the user. We have little control or visibility over that. The user then leaves the company and we remove them from AD. Will the user still be able to access jenkins using the API token?

Thanks.

**Comment by gavinfish** [comment]
@philwinder I would recommend you to remove the users from Jenkins too.

**Comment by philwinder** [comment]
@gavinfish What would happen if you didn't? Would they still have access?

**Comment by iomarcovalente** [comment]
> @gavinfish What would happen if you didn't? Would they still have access?

Yes, if you don't remove them from Jenkins they would have access to all allowed operations by their user's permissions via the API. Find more about this here https://www.cyberark.com/threat-research-blog/securing-jenkins-active-directory-and-ldap-services-in-jenkins-environment/

**Comment by iomarcovalente** [comment]
Following up on this issue I had a question though: is there a way to authenticate with jenkins via the azure-ad-plugin through the CLI?

That is, I have a service account in azure that I would like to use to authenticate with Jenkins. I have username and password of said service account but cannot find a way to authenticate via the CLI as opposed to log in to Jenkins.

If I try logging in with `curl '<jenkinsURL>/me/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken' \
--data 'newTokenName=test-token' \
--user '<username>:<password>'`

I would only get:
```
java.lang.IllegalStateException: Unexpected authentication type: org.acegisecurity.providers.UsernamePasswordAuthenticationToken@7c13563f: Username: ott-nft-jenkins; Password: [PROTECTED]; Authenticated: false; Details: org.acegisecurity.ui.WebAuthenticationDetails@ffffa64e: RemoteIpAddress: 10.119.10.141; SessionId: null; Not granted any authorities
	at com.microsoft.jenkins.azuread.AzureSecurityRealm$3.authenticate(AzureSecurityRealm.java:268)
	at jenkins.security.BasicHeaderRealPasswordAuthenticator.authenticate(BasicHeaderRealPasswordAuthenticator.java:56)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:79)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
```

**Comment by philwinder** [comment]
Thanks for the confirmation @iomarcovalente!

**Comment by eduardo-banuelos-by** [comment]
Hello I am receiving an error with this exact same method. 
< HTTP/2 500 > and just a barely visible HTML website
As @philwinder mentioned, I also started with the Azure AD token but jumped back to the Jenkins token. 

Is there any update needed on the plug-in that could be causing this?

**Comment by timja** [comment]
Please don’t post on years old issues. Things have moved on a lot
