### ISSUE TITLE
Old Azure AD description in README

### ISSUE THREAD

**Issue by rioriost** [jenkinsci/azure-ad-plugin#56]
There is no longer **Required Permissions** in the blade in an app.
https://docs.microsoft.com/en-us/azure/active-directory/develop/app-registrations-training-guide#required-permissionsapi-permissions

> Option 1:
> 
> Give Jenkins permission to Read directory data in Azure Active Directory to get autocompletion support in Azure Active Directory Matrix
> 
> In Application setting page, click Required Permissions and select Windows Azure Active Directory, then select Read directory data permissions in Application permissions section

Would you please update the description with the new UI in Azure Portal or Azure CLI?

**Comment by Pistahh** [comment]
Agreed, the config description in the docs hardly matches what is actually seen in the Azure UI. I always struggle with the config and waste a lot of time figuring out when something just doesn't work and all I see is cryptic error messages. Would it be possible to completely review the docs and update them?

**Comment by pduchnovsky** [comment]
#96
