### ISSUE TITLE
Error message: Insufficient privileges to complete the operation.

### ISSUE THREAD

**Issue by leonjyq** [jenkinsci/azure-ad-plugin#560]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

![Uploading image.png…]()

### Reproduction steps

1. Follow the https://plugins.jenkins.io/azure-ad/#plugin-content-setup-in-microsoft-entra-id and https://plugins.jenkins.io/azure-ad/#plugin-content-setup-in-microsoft-entra-id to configure an application in our Microsoft EntraID.
2. Follow https://plugins.jenkins.io/azure-ad/#plugin-content-authentication to fill in the credentials.
3. Click on **Verify configuration**.

### Expected Results

Pass the verification

### Actual Results

![image](https://github.com/jenkinsci/azure-ad-plugin/assets/5651983/0662b600-e285-4fd7-b70f-6f9e300b94c3)

**Comment by leonjyq** [comment]
The API permission has also been added.
<img width="598" alt="image" src="https://github.com/jenkinsci/azure-ad-plugin/assets/5651983/0e058e35-a692-4ab5-a533-b36f75c6f769">

**Comment by timja** [comment]
You need to add Application permissions not delegated permissions.

**Comment by leonjyq** [comment]
> You need to add Application permissions not delegated permissions.

Thanks for the reply, let me try to test it out.
