### ISSUE TITLE
User with full access missing the Overall/Read permission

### ISSUE THREAD

**Issue by lukasy-a** [jenkinsci/azure-ad-plugin#63]
I am receiving this initial error on log in to Jenkins via Azure AD plugin:

> _Access Denied
> lukas.ycas@cujo.com is missing the Overall/Read permission_

I am using Azure AD Matrix-based security, I've tested this on a Azure AD group with full checkmarks on all privileges (full access) and on user with full privileges, I still get this access denied error.

What causes this and how to fix? 

P.S. is it expected that when user has no access to the app via Azure AD he gets this stacktrace of ..:
```
java.lang.IllegalStateException: Can't extract id_token
	at com.microsoft.jenkins.azuread.AzureSecurityRealm.doFinishLogin(AzureSecurityRealm.java:205)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
....
```

**Comment by amansilla** [comment]
I've the same issue after upgrading the plugin to 1.1.2.

**Comment by gavinfish** [comment]
@amansilla Before the upgrade, it works properly? Which version did you use?

**Comment by amansilla** [comment]
@gavinfish with versions older than 1.0.0 never had an issue.

**Comment by gavinfish** [comment]
@amansilla Did you follow [this](https://github.com/jenkinsci/azure-ad-plugin#version-100-migration-instruction)?

**Comment by amansilla** [comment]
@gavinfish yes, in my case jenkins was already running with HTTPS so I skipped step 1.

Maybe this info may help: Jenkins runs behind a AWS load balancer which implements HTTPS.

**Comment by gavinfish** [comment]
@amansilla please refer to #32

**Comment by lukasy-a** [comment]
@amansilla 
which issue are you refering to? "cannot extract id_token" or the Overall/Read permission?

I have managed to solve the Overall/Read permission by granting access the following way, when filling out the new role in Azure AD Matrix Security:
1. Type in the required user, for example: lukas.ycas
2. The dropdown (if you have it working) will suggest you lukas.ycas (aaaa-bbbb-ccccc...) the Azure object ID basically, do not use it, instead enter in as following:
lukas.ycas (lukas.ycas@cujo.com)

Now I no longer receive the error, and can use azure AD plugin even with API.

Not sure if this works on Azure AD security groups though.

**Comment by amansilla** [comment]
@gavinfish I don't think my issue is related to #32, since `ID tokens` under `Implicit grant` is enabled in my case. I don't get any stacktrace related to `Can't extract id_token` as explained here in the first comment. My issue is only related to the message which happens randomly:

> Access Denied
antonio.mansilla@flagbit.de is missing the Overall/Read permission

**Comment by amansilla** [comment]
> @amansilla
> which issue are you refering to? "cannot extract id_token" or the Overall/Read permission?
> 
> I have managed to solve the Overall/Read permission by granting access the following way, when filling out the new role in Azure AD Matrix Security:
> 
> 1. Type in the required user, for example: lukas.ycas
> 2. The dropdown (if you have it working) will suggest you lukas.ycas (aaaa-bbbb-ccccc...) the Azure object ID basically, do not use it, instead enter in as following:
>    lukas.ycas ([lukas.ycas@cujo.com](mailto:lukas.ycas@cujo.com))
> 
> Now I no longer receive the error, and can use azure AD plugin even with API.
> 
> Not sure if this works on Azure AD security groups though.

My issue is the Access Denied but in my case we never use Azure AD users for authorization, instead we always use groups for everything.

**Comment by lukasy-a** [comment]
@amansilla you could test if the prefix I gave you works with groups.

@gavinfish the cannot extract id token also doesnt relate to #32 for me, since I also have Implicit grant enabled. This confuses some of my users which do not have access to the app 'that they do have access but Jenkins is down, throwing errors, etc.'

**Comment by gavinfish** [comment]
@amansilla My api permissions for the app is like below:
![aad-permission](https://user-images.githubusercontent.com/6169722/72066696-38025800-331c-11ea-900f-deb5a5512e34.png)

@lukasy-a thanks for sharing the information. Do you mean when a user who does not have access to the aad app login the Jenkins server, the server will throw errors?

**Comment by amansilla** [comment]
@gavinfish my permissions look good.

![API permissions - Microsoft Azure](https://user-images.githubusercontent.com/1576983/72068238-e12d5c00-32e4-11ea-98a5-db2f07b26d39.png)

Just to figure out how my Jenkins instance looks like:
* Jenkins 2.190.3
* Azure AD 1.1.2
* Security Realm: Azure Active Directory
* Authorization: Azure Active Directory Matrix-based security where `Anonymous Users` and `Authenticated Users` have no permissions enabled and there is only two groups from AzureAD (sec_JENKINS_READ and sec_JENKINS_ADMIN) which have overall read and overall admin enabled respectively.

**Comment by ep4sh** [comment]
The same for me. I've created a service account for triggering jobs via curl and I'm able to login with it successfully, all permissions exist and I am able to fetch the needed API endpoint.

But when I use curl and pre-generated API token I get an error:
```
svc_jenkins@host.com is missing the Overall/Read permission
```


AzureAD plugin: 1.2.1

**Comment by ep4sh** [comment]
I've solved this specifying in AzureAD Matrix user (as long as an existing group) with '@':
like user@host.com - and add permissions for it.

**Comment by hikkyXII** [comment]
Hello everyone!
Adding email to user in "Azure Active Directory Matrix-based security" works too.
Like: User Name (Azure object ID) (email)

**Comment by timja** [comment]
I believe fixed by https://github.com/jenkinsci/azure-ad-plugin/releases/tag/150.vb3db9f880321

**Comment by honomoa** [comment]
Use `GROUP:Overall/Administer:lukas.ycas@cujo.com` instead of `USER:Overall/Administer:lukas.ycas@cujo.com`
