### ISSUE TITLE
Jenkins Azure active directory SSO is having /securityRealm/finishLogin issue in Microsoft  GCC High

### ISSUE THREAD

**Issue by Judedouard3** [jenkinsci/azure-ad-plugin#637]
Entra ID plugins is able to work while login as admin in Jenkins. I am able to setup azure active directory and able to pick user and group in ADD. When I logout from Jenkins admin user and try to log in with AAD users with SSO, after choosing the user and prompts to the site, it states that the site is taking too long. I changed the R to r in /securityRealm/finishLogin in the API, and when I reset Jenkins, it comes back with redirect Url is incorrect with the R still being uppercase and not lower case. Also, user and groups are only picked up by disabling Graph.

**Comment by timja** [comment]
Please use the bug report template and provide step by step instructions, I can't follow this

https://github.com/jenkinsci/azure-ad-plugin/issues/new?template=1-report-bug.yml
