### ISSUE TITLE
Security Realm redirect URI has been changing after version upgrade from Jenkins 2.462.3 to Jenkins 2.479.2 LTS

### ISSUE THREAD

**Issue by johndevopsus** [jenkinsci/azure-ad-plugin#647]
After the version upgrade from Jenkins 2.462.3 to Jenkins 2.479.2 LTS, Redirect URIs: https://URL.com/securityRealm/finishLogin being changed to '**https**://DOMAIN.com:8080/securityRealm/finishLogin.  So, the Azure Active Directory cannot be redirected. Jenkins is installed on Windows.

AADSTS50011: The redirect URI 'https://DOMAIN.com:8080/securityRealm/finishLogin' specified in the request does not match the redirect URIs configured for the application '<APP-ID>'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

I tried updating the redirect URI in Azure App Registration to 'https://DOMAIN.com:8080/securityRealm/finishLogin,' but it did not solve the issue.

Thank you

**Comment by timja** [comment]
Probably something to do with this:
https://www.jenkins.io/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/

**Comment by johndevopsus** [comment]
Hi @timja 
Thank you for the response, but the current version  2.462.3 is running fine, and the IIS settings have not been changed. When we updated Jenkins to 2.479.2 LTS, we got the error below. If the issue is related to IIS, it is not supposed to work on the current version.

AADSTS50011: The redirect URI 'https://domain.com:8080/securityRealm/finishLogin' specified in the request does not match the redirect URIs configured for the application ''. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

**Comment by timja** [comment]
https://www.jenkins.io/changelog-stable/2.479.1/ includes upgrading Jetty from 10.x to 12.x.

I suspect something in there is causing your issue.

Jenkins thinks that you are coming in on port 8080 for some reason.

What is configured in your Jenkins URL in system configuration?

**Comment by timja** [comment]
Duplicate of https://issues.jenkins.io/browse/JENKINS-73667 please follow up there
