### ISSUE TITLE
Group support doesn't work if user has >150 groups

### ISSUE THREAD

**Issue by DavidTheSysAdmin** [jenkinsci/azure-ad-plugin#75]
If a user is a member of more than 150 groups, the JWT will have a link to the Microsoft API to fetch the complete list. In our testing it seems that Jenkins is not getting group membership when a group claim uses a callback URL.
In Microsoft's documentation about [Access Tokens](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens):
"...if the number of groups the user is in goes over a limit (150 for SAML, 200 for JWT), then an overage claim will be added to the claim sources pointing at the AAD Graph endpoint containing the list of groups for the user..."
I found a similar issue [here](https://github.com/pac4j/pac4j/issues/745). Looking at the azure-ad-plugin's dependencies it looks like it is using ADAL4J which is in maintenance mode and will not be getting new feature updates. Perhaps migrating to [MSAL for java](https://github.com/AzureAD/microsoft-authentication-library-for-java) might fix this problem?

**Comment by gavinfish** [comment]
cc @xuzhang3 @mybayern1974 @lrxtom2

**Comment by DavidTheSysAdmin** [comment]
Is this in the pipeline to be addressed anytime soon?

**Comment by dsargent3220** [comment]
We are having this issue as well.  Upvote!  :)

**Comment by lrxtom2** [comment]
Hi, We are still investigating the issue, thanks for that.

**Comment by azuroff** [comment]
+1 - we're running into the same issue.

**Comment by azuroff** [comment]
We found a way to get the groups we need for Jenkins returned in the id token, even if the user is over the 200 group limit -

1. Assign the group(s) to the AAD application.
2. In the application manifest, change the **groupMembershipClaims** value to **ApplicationGroup**

This will return only the groups that are assigned to the application that the user is a member of - which is all Jenkins really needs.

Reference: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims#configure-the-azure-ad-application-registration-for-group-attributes

**Comment by DavidTheSysAdmin** [comment]
> We found a way to get the groups we need for Jenkins returned in the id token, even if the user is over the 200 group limit -
> 
> 1. Assign the group(s) to the AAD application.
> 2. In the application manifest, change the **groupMembershipClaims** value to **ApplicationGroup**
> 
> This will return only the groups that are assigned to the application that the user is a member of - which is all Jenkins really needs.
> 
> Reference: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims#configure-the-azure-ad-application-registration-for-group-attributes

Thanks for the information azuroff, that's actually really useful for some other stuff I'm working on. 
However for our jenkins implementation we would prefer to have the flexibility to allow our users to use any group they want without having to request it be assigned to the application. Besides, claim  callbacks are a part of the saml standard, not supporting this standard feature is a bug and should be addressed.

**Comment by mibzzz** [comment]
We are also impacted by this issue and are looking for workarounds.
Is there any approximate date when it will be fixed?

**Comment by timja** [comment]
For anyone interested there is a test build here: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/azure-ad/153.vfa95a4ba16c3/azure-ad-153.vfa95a4ba16c3.hpi

Please report any feedback in https://github.com/jenkinsci/azure-ad-plugin/pull/118
