### ISSUE TITLE
What is Read directory data required by this plugin?

### ISSUE THREAD

**Issue by chrispat** [jenkinsci/azure-ad-plugin#8]
I am able to configure Gitlab integration with Azure Active Directory with no admin level permissions.  It would be nice to be able to configure Jenkins that way as well.

**Comment by monkeyhandz** [comment]
Is there any timeline for when this permission requirement will be removed?
Its stopping us from using this plugin as our system admins are pointing out other SSO integrations don't need it. If it can't be turned off then it would be helpful to understand why its needed for jenkins.

**Comment by gavinfish** [comment]
Hi @monkeyhandz , this plugin uses the permission for autocomplete of matrix authorization. I will try to fetch data like object id.

**Comment by gsacavdm** [comment]
Why does it need Read Directory and not Read Users?

**Comment by timja** [comment]
Not required as of https://github.com/jenkinsci/azure-ad-plugin/pull/52

Note: auto completion won't work for usernames on the security page if you use this approach
