### ISSUE TITLE
calling this plugin via REST API

### ISSUE THREAD

**Issue by adelwin** [jenkinsci/azure-ad-plugin#82]
I use this plugin to manage authentication and authorization of our Jenkins instance.
I am trying to do use account life-cycle management from an outside system.
I was able to trace the rest URL used by the UI to search for users and to add users.
But it seems that this plugin is highly dependent on cookies and/or session-id ?

Can anyone clarify if this is really the case?
Or am I doing it wrong ?

Also jenkins-cli seems to no longer be working

**Comment by timja** [comment]
Fixed in https://github.com/jenkinsci/azure-ad-plugin/releases/tag/150.vb3db9f880321
