### ISSUE TITLE
Settings verified, infinite redirect loop

### ISSUE THREAD

**Issue by Myrdrahl** [jenkinsci/azure-ad-plugin#83]
We are running Jenkins on a Windows server, with IIS as a reverse proxy. We have been running authentication with LDAP but are now in the process of moving to Azure AD. We are experiencing issues with authenticating and it seems like we are stuck in an infinite redirect/nonce-loop. 

Symptoms and steps taken:

After configuring the clientID, tenantID and secret, we are able to verify the settings within the plugin in Jenkins. Everything looks a-ok! After saving, we can then add users, which auto-complete from lookup in Azure. However, immideately after saving the user matrix, we end up in a redirect loop, with the nonce constantly refreshing like crazy. This happens before even getting a login screen. 

Tried using different browers, clearing cache and even incognito mode - all ineffective to solve the issue. 

Inspecting the headers, it seems that all authentication seem to be directed at our jenkins server, there seem to be no redirection to azure for authentication. Did we miss something here, or is this normal behaviour? Also, do we need to set any special header redirects in IIS for this authentication to work as intended?

**Comment by Myrdrahl** [comment]
After inspecting headers in my browser, I find this: "
x-you-are-authenticated-as: anonymous" anonymous obviously have no authorization. However, I never get prompted for any credentials, so I'm still stuck.

**Comment by Myrdrahl** [comment]
For testing purposes, we tried configuring a docker container in a Linux environment with nginx as a reverse proxy - this worked perfectly, first try.

**Comment by timja** [comment]
No idea why, sounds related to your reverse proxy and not this plugin

**Comment by gtbuchanan** [comment]
Just in case anybody comes back to this later, the solution is to disable the "Reverse rewrite host in response headers" option in ARR (IIS -> Application Request Routing -> Server Proxy Settings). For whatever reason, it rewrites the host in the `Location` header even if the header doesn't contain the proxy host.
