### ISSUE TITLE
Automate Adding users in jenkins

### ISSUE THREAD

**Issue by jyothibasuk** [jenkinsci/azure-ad-plugin#85]
I have my Azure AD connected to Jenkins. post this step, I am manually adding users and configuring their roles.

is there any automation possibility that I can take a user from Azure AD and add as a user in Jenkins and assign an initial or basic rule (like read-only).

**Comment by dafelipe130** [comment]
Kind of having a similar problem. 

I have to manually add service accounts by logging in to Jenkins via the service account. Is there a way to define that service account in Jenkins without me logging as it initially?

I'm using JCasC btw.

**Comment by timja** [comment]
Use JCasC?

![image](https://user-images.githubusercontent.com/21194782/113927238-1de84b80-97e5-11eb-832d-61b4fdccb17e.png)


![image](https://user-images.githubusercontent.com/21194782/113927279-2d679480-97e5-11eb-8734-a7dae6b0a0a5.png)

The UI doesn't validate the user actually exists, what do you need the service account for? You'll need to login once (or script it) if you are using the account for rest access via API token

**Comment by dafelipe130** [comment]
@timja Yeah, I use JCasC to provide the service account with the privileges but am hoping for a way to add the account to the "People" list as well without having to login manually or doing it through a script.

**Comment by timja** [comment]
What do you need it in people for?

**Comment by dafelipe130** [comment]
I need a specified user to satisfy the [authorize project plugin](https://github.com/jenkinsci/authorize-project-plugin).

**Comment by timja** [comment]
The simplest way would be to use a groovy script that creates the user if it doesn’t exist either with the configuration as code groovy plugin or as a groovy init script

**Comment by timja** [comment]
Running `User.get("my-user@example.com", true)` via a groovy script / script console should do it for you.

I don't think the functionality belongs in this plugin you can easily script to work around it
