### ISSUE TITLE
id_token wrongfully described as optional?

### ISSUE THREAD

**Issue by audunsolemdal** [jenkinsci/azure-ad-plugin#88]
Referring to the read-me

If I do not check the id_token under implicit grant for my app registration, users end up here after entering AAD credentials

![image](https://user-images.githubusercontent.com/21334768/96244046-d7d4cc80-0fa5-11eb-8075-2fabb2ad451b.png)

This is only mentioned under "group" support

id_token also needs admin consent in for our organization in order to not spam requests for every new signin.

**Comment by timja** [comment]
correct I've rewrote the docs in https://github.com/jenkinsci/azure-ad-plugin/pull/118
