### ISSUE TITLE
Unable to add users and groups to AAD Matrix-based security

### ISSUE THREAD

**Issue by audunsolemdal** [jenkinsci/azure-ad-plugin#89]
![image](https://user-images.githubusercontent.com/21334768/96245494-a957f100-0fa7-11eb-9a15-83ba04189e0d.png)

I am only able to add myself (AULS@equinor.com) by being the admin user in config.xml

If this is set, I am able to use the jenkins instance, but I am unable to add other users or groups.

I have tried different patterns to add users and groups, none successful. 

I have not been granted admin permissions e.g. Directory.Read.All, but used the other options mentioned.

**Comment by hikkyXII** [comment]
Hi
At lease read permissions are required.
Worked for me: https://medium.com/@seifeddinemouelhi/configure-azure-active-directory-with-jenkins-e6ea31fb833e

**Comment by audunsolemdal** [comment]
Is there a way to have this work without the Directory.Read.All permission? My tenant admins do not grant this permission

**Comment by hikkyXII** [comment]
Not sure about that.

**Comment by timja** [comment]
You just need to put the users in the right format,

`Display Name (Object ID)`

e.g. 

Tim Jacomb (c994450c-daec-4b4c-afc7-dd0980ee44c7)

Or use one of the other authorization strategies and use the Jenkins ID,

Docs coming in https://github.com/jenkinsci/azure-ad-plugin/pull/118

**Comment by afdgtech** [comment]
Hi Did you ever get this to work? I am having the same issue and  I am on version Version: 340.vdef002cf6415 and I have following permissions below. If I use Azure Security matrix it doesn't show anything. I have to use the regular security Matrix and enter user or group object ID and that works. But would be much nicer if I can use the Azure ad so we do not have to look up object ids. Anyone have any ideas? Thank you

Directory.Read.All/Application
email/Delegated
Group.Read.All/Application
Group.Read.All/Application
People.Read.All/Application
People.Read.All/Application
User.Read.All/Application
