### ISSUE TITLE
Add an option to add a "fallback" login method with username and password

### ISSUE THREAD

**Issue by eranreshef** [jenkinsci/azure-ad-plugin#92]
I am using this plugin as the authentication method for my jenkins instance but I would like to have the option to define a "fallback" username and password in case I lost the connectivity to the AD service. Is it possible?

**Comment by davidslee9-sme** [comment]
TO add to this request, is it possible to exclude certain users from authenticating against Azure AD?   We use perforce commit hooks to kick off builds in Jenkins and it uses a perforce username/pass in jenkins to authenticate using normal jenkins auth.

**Comment by timja** [comment]
> TO add to this request, is it possible to exclude certain users from authenticating against Azure AD? We use perforce commit hooks to kick off builds in Jenkins and it uses a perforce username/pass in jenkins to authenticate using normal jenkins auth.

After https://github.com/jenkinsci/azure-ad-plugin/pull/112 is merged then you will be able to use API tokens which is the standard way to do this.



> I am using this plugin as the authentication method for my jenkins instance but I would like to have the option to define a "fallback" username and password in case I lost the connectivity to the AD service. Is it possible?

I don't think so, no other Jenkins security realm plugin supports this and I don't think we should be the first, unless anyone has any better information on this or other precedent / examples I'm closing to close this

**Comment by mark00s** [comment]
https://plugins.jenkins.io/active-directory/#plugin-content-fall-back-user
