### ISSUE TITLE
Please help with Azure China

### ISSUE THREAD

**Issue by PoseyZhong** [jenkinsci/azure-ad-plugin#93]
Failed to verify the Application with Azure China.

Tried to replace the url in Utils.java and Constants.java with Azure China url, rebuild it. Still get the error :  java.io.IOException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS90002: Tenant '05958bb9-f8aa-4852-a20f-7ede79071ff8' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: 328a6b54-10f1-403e-95a5-64dda1604e00\r\nCorrelation ID: 388ddb92-c289-4d0c-9d09-75ebc983ad08\r\nTimestamp: 2020-12-17 10:26:44Z","error":"invalid_request","error_uri":"https:\/\/login.microsoftonline.com\/error?code=90002"}

**Comment by timja** [comment]
You also need to update the AzureEnvironment in https://github.com/jenkinsci/azure-ad-plugin/blob/670899d66cb2211fdcadee2992295f6a6ca965b8/src/main/java/com/microsoft/jenkins/azuread/AzureSecurityRealm.java#L101

and there's another reference for verifying the configuration.

PR welcome to make this more configurable, I just can't test it as I don't have access to the sovereign clouds

**Comment by timja** [comment]
tracked in https://github.com/jenkinsci/azure-ad-plugin/issues/60
